/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 598e07d34e1b
 */

export interface Logger {
  group(label?: string): void;
  groupEnd(): void;
  log(message: any, ...args: any[]): void;
}
