/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import {
  LegacyError,
  LegacyError$inboundSchema,
  LegacyError$Outbound,
  LegacyError$outboundSchema,
} from "./legacy-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  StructuredError,
  StructuredError$inboundSchema,
  StructuredError$Outbound,
  StructuredError$outboundSchema,
} from "./structured-error.js";

/**
 * Pumble returns one of two error body shapes; clients should be prepared
 *
 * @remarks
 * to parse either. See the parent operation description for context.
 */
export type ErrorT = LegacyError | StructuredError;

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> =
  smartUnion([LegacyError$inboundSchema, StructuredError$inboundSchema]);
/** @internal */
export type ErrorT$Outbound = LegacyError$Outbound | StructuredError$Outbound;

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<
  ErrorT$Outbound,
  z.ZodTypeDef,
  unknown
> = smartUnion([LegacyError$outboundSchema, StructuredError$outboundSchema]);

export function errorToJSON(errorT: ErrorT): string {
  return JSON.stringify(ErrorT$outboundSchema.parse(errorT));
}
export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}
