/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as types from "../../types/primitives.js";
import { PumbleSDKError } from "./pumble-sdk-error.js";

/**
 * Free-form error message from the request handler layer.
 */
export type LegacyErrorData = {
  /**
   * Human-readable error message.
   */
  error: string;
};

/**
 * Free-form error message from the request handler layer.
 */
export class LegacyError extends PumbleSDKError {
  /**
   * Human-readable error message.
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: LegacyErrorData;

  constructor(
    err: LegacyErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "LegacyError";
  }
}

/** @internal */
export const LegacyError$inboundSchema: z.ZodType<
  LegacyError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: types.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new LegacyError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type LegacyError$Outbound = {
  error: string;
};

/** @internal */
export const LegacyError$outboundSchema: z.ZodType<
  LegacyError$Outbound,
  z.ZodTypeDef,
  LegacyError
> = z.instanceof(LegacyError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
  }));
