/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bcd9e1300472
 */

import { channelsGetChannel } from "../../funcs/channels-get-channel.js";
import * as operations from "../../models/operations/index.js";
import * as types from "../../types/primitives.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: types.optional(operations.GetChannelRequest$inboundSchema),
};

export const tool$channelsGetChannel: ToolDefinition<typeof args> = {
  name: "channels-get-channel",
  description: `Get channel details by ID or name

Provide **either** \`channelId\` (preferred) **or** \`channel\` (by name).
The response wraps the channel in \`{ channel: ... }\` (mirroring
\`listChannels\`), without the \`pinnedMessages\` / \`users\` fields.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await channelsGetChannel(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
