/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { channelsRemoveUserFromChannel } from "../../funcs/channels-remove-user-from-channel.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveUserFromChannelRequest$inboundSchema,
};

export const tool$channelsRemoveUserFromChannel: ToolDefinition<typeof args> = {
  name: "channels-remove-user-from-channel",
  description: `Remove a user from a channel`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await channelsRemoveUserFromChannel(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
