/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { channelsCreateChannel } from "../../funcs/channels-create-channel.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateChannelRequest$inboundSchema,
};

export const tool$channelsCreateChannel: ToolDefinition<typeof args> = {
  name: "channels-create-channel",
  description: `Create a new channel

Creates a new public or private channel. The caller becomes the
channel creator and is added as a member.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await channelsCreateChannel(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
