/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 11a7a0552753
 */

import { channelsListChannels } from "../../funcs/channels-list-channels.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$channelsListChannels: ToolDefinition = {
  name: "channels-list-channels",
  description: `List all channels

Returns every channel visible to the API key.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await channelsListChannels(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
