/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 40b5ad521c32
 */

import { channelsAddUsersToChannel } from "../../funcs/channels-add-users-to-channel.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AddUsersToChannelRequest$inboundSchema,
};

export const tool$channelsAddUsersToChannel: ToolDefinition<typeof args> = {
  name: "channels-add-users-to-channel",
  description: `Add users to a channel`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await channelsAddUsersToChannel(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
