/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0010200503b3
 */

import { messagesSearchMessages } from "../../funcs/messages-search-messages.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SearchMessagesRequest$inboundSchema,
};

export const tool$messagesSearchMessages: ToolDefinition<typeof args> = {
  name: "messages-search-messages",
  description: `Search messages

Searches messages by free text, sender, channel, and/or time window.
At least one of \`text\`, \`from\`, or \`in\` is required.

## Pagination
Cursor input is \`beforeTs\` (epoch ms); the next cursor is the
\`timestampMilli\` of the oldest hit in the current page. **Edge case**:
Pumble returns timestamps truncated to seconds, so messages sharing
the same \`timestampMilli\` that straddle a page boundary can be
skipped. For low-volume channels or \`limit >= 10\`, this is rarely
observed; for high-volume bursts use a smaller search window via
\`afterTs\` to bound the result set.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesSearchMessages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
