/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 00d37de496fe
 */

import { messagesListMessages } from "../../funcs/messages-list-messages.js";
import * as operations from "../../models/operations/index.js";
import * as types from "../../types/primitives.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: types.optional(operations.ListMessagesRequest$inboundSchema),
};

export const tool$messagesListMessages: ToolDefinition<typeof args> = {
  name: "messages-list-messages",
  description: `List messages in a channel

Retrieves a paginated list of messages from a channel. Pagination is
cursor-based: pass the \`id\` of the last returned message as the next
\`cursor\`. \`hasMoreBefore\` / \`hasMoreAfter\` indicate which direction
still has messages relative to the cursor.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesListMessages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
