/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 353432c079b7
 */

import { messagesSendMessage } from "../../funcs/messages-send-message.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SendMessageRequest$inboundSchema,
};

export const tool$messagesSendMessage: ToolDefinition<typeof args> = {
  name: "messages-send-message",
  description: `Send a message to a channel

Sends a text (or rich-text) message. Provide **either** \`channelId\`
(preferred) **or** \`channel\` (by name). If \`threadRootId\` is set, the
message is posted as a reply in that thread (equivalent to
\`sendReply\`).
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesSendMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
