/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e6881f121f92
 */

import { messagesRemoveReaction } from "../../funcs/messages-remove-reaction.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveReactionRequest$inboundSchema,
};

export const tool$messagesRemoveReaction: ToolDefinition<typeof args> = {
  name: "messages-remove-reaction",
  description: `Remove a reaction from a message`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesRemoveReaction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
