/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 08f16e601c80
 */

import { messagesDmUser } from "../../funcs/messages-dm-user.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DmUserRequest$inboundSchema,
};

export const tool$messagesDmUser: ToolDefinition<typeof args> = {
  name: "messages-dm-user",
  description: `Send a direct message to a user

Opens (or reuses) a 1-to-1 DM channel and posts a message. The
response's \`channelId\` is the DM channel — useful for follow-up
operations.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesDmUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
