/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0cfe58db2b7e
 */

import { messagesDeleteMessage } from "../../funcs/messages-delete-message.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteMessageRequest$inboundSchema,
};

export const tool$messagesDeleteMessage: ToolDefinition<typeof args> = {
  name: "messages-delete-message",
  description: `Delete a message by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesDeleteMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
