/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbd7c45ecfc5
 */

import { messagesAddReaction } from "../../funcs/messages-add-reaction.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AddReactionRequest$inboundSchema,
};

export const tool$messagesAddReaction: ToolDefinition<typeof args> = {
  name: "messages-add-reaction",
  description: `Add a reaction (emoji) to a message

Adds a reaction code in \`:emoji_name:\` form. Pumble enforces the
colon-wrapped form server-side; bare names (e.g. \`+1\`) return 403.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesAddReaction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
