/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 82daed6941a2
 */

import { scheduledMessagesEditScheduledMessage } from "../../funcs/scheduled-messages-edit-scheduled-message.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EditScheduledMessageRequest$inboundSchema,
};

export const tool$scheduledMessagesEditScheduledMessage: ToolDefinition<
  typeof args
> = {
  name: "scheduled-messages-edit-scheduled-message",
  description: `Edit a scheduled message

Updates a queued scheduled message. **All of** \`scheduledMessageId\`,
\`channelId\`, \`text\`, and \`sendAt\` are required server-side — omitting
any of them returns 403 with \`[must not be null]\`. Pass the existing
\`sendAt\` value verbatim if you don't want to reschedule.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await scheduledMessagesEditScheduledMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
