/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersCustomStatus } from "../../funcs/users-custom-status.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CustomStatusRequest$inboundSchema,
};

export const tool$usersCustomStatus: ToolDefinition<typeof args> = {
  name: "users-custom-status",
  description: `Update the custom status of the authenticated user

Sets or clears the user's custom status. **Both** \`code\` and
\`expiresAt\` are required server-side. Pass an \`expiresAt\` far in the
future for a "don't auto-clear" effect; pass a past timestamp to
immediately clear.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersCustomStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
