/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersMyInfo } from "../../funcs/users-my-info.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$usersMyInfo: ToolDefinition = {
  name: "users-my-info",
  description: `Get info about the authenticated user

Returns the user record for whichever account owns the API key.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await usersMyInfo(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
