/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8a007b735411
 */

import { usersListUserGroups } from "../../funcs/users-list-user-groups.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$usersListUserGroups: ToolDefinition = {
  name: "users-list-user-groups",
  description: `List workspace user groups`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await usersListUserGroups(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
