/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 32911c70c254
 */

import { usersListUsers } from "../../funcs/users-list-users.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$usersListUsers: ToolDefinition = {
  name: "users-list-users",
  description: `List all workspace users

Returns every user in the workspace as a flat array.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await usersListUsers(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
