// Hand-written extension. NOT regenerated by Speakeasy - safe to edit.

import type { ChannelSummary, UserSummary } from "./client.js";

export function displayChannel(channel: ChannelSummary): string {
  return channel.name.startsWith("#") ? channel.name : `#${channel.name}`;
}

export function displayUser(user: UserSummary): string {
  return user.name.trim().length > 0 ? user.name : user.email;
}
