// Hand-written extension. NOT regenerated by Speakeasy — safe to edit.
//
// Robust async-iterator wrapper around messages.searchMessages that walks
// every page defensively, deduping by message id and using a min-timestamp
// cursor step to avoid both infinite loops and unnecessary re-requests.
//
// Background quirks, also summarized in README.md:
//   * Pumble paginates searchMessages by the `beforeTs` cursor (epoch ms,
//     strictly less than).
//   * Server-side timestamps are truncated to seconds, so two messages
//     sharing a `timestampMilli` can straddle a page boundary. The naive
//     cursor (= last item's timestampMilli) can re-request a page that
//     only contains already-seen ids, looping forever or burning quota.
//
// This helper walks pages defensively:
//   * Tracks seen ids; never yields the same hit twice.
//   * Computes the next `beforeTs` as min(timestampMilli of this page) - 1,
//     so we never re-request the page we just consumed.
//   * Stops when the API signals `hasMore === false` AND the page is
//     short, or when the page's first id matches the previous page's
//     first id (server loop), or when a full page yields no new ids
//     after dedupe.
//   * Tolerates hits missing `timestampMilli` (defensive — non-spec).
//
// The trade-off: in the rare case that >limit messages share an identical
// truncated-to-seconds timestamp at a page boundary, the dropped ones
// inside that second cannot be retrieved with `beforeTs` alone — the
// caller should narrow the window with `afterTs` for high-volume bursts.

import type { SearchHit } from "../models/search-hit.js";
import type { SearchMessagesRequest } from "../models/operations/search-messages.js";

/**
 * Minimal duck-typed client interface: anything that exposes
 * `messages.searchMessages(...)` returning a page-iterable response.
 *
 * In practice the caller passes a `PumbleSDK` instance or its
 * `.messages` subclient — but typing it structurally keeps this
 * helper testable without dragging in the whole SDK type graph.
 */
export interface SearchAllClient {
  messages: {
    searchMessages(
      request: SearchMessagesRequest,
    ): Promise<SearchAllPageResult>;
  };
}

/**
 * Shape of one page as returned by `messages.searchMessages(...)`.
 * `result` is the raw `SearchMessagesResult` body; the response object
 * is also an async iterable that yields successive pages. We do NOT
 * use that iterable here — we drive the cursor manually to dedupe and
 * apply the defensive stop conditions.
 */
export interface SearchAllPageResult {
  result: {
    content: SearchHit[];
    totalElements: number;
    hasMore: boolean;
  };
}

export interface SearchAllOptions {
  /**
   * AbortSignal to cancel the walk mid-flight. If aborted, the
   * generator throws the signal's `reason` (or a DOMException-shaped
   * AbortError if no reason was provided).
   */
  signal?: AbortSignal;
  /**
   * Stop yielding once this many hits have been produced. The current
   * page is fully drained before the limit takes effect, so the
   * caller may observe slightly more or fewer hits than this value
   * depending on dedupe behaviour — but never more than
   * `maxResults + page.length`.
   */
  maxResults?: number;
  /**
   * Override the hard 10 000-page safety cap. Useful for tests; in
   * production code prefer a tighter `maxResults` instead.
   */
  maxPages?: number;
  /**
   * Optional observer fired once per fetched page (after dedupe but
   * before yields). Use it for progress reporting or rate-limit
   * smoothing. Throwing from `onPage` aborts the walk.
   */
  onPage?: (
    page: SearchAllPageResult,
    info: { pageIndex: number; newInPage: number; yielded: number },
  ) => void | Promise<void>;
}

class AbortError extends Error {
  override readonly name = "AbortError";
}

function throwIfAborted(signal: AbortSignal | undefined): void {
  if (!signal?.aborted) return;
  const reason = (signal as AbortSignal & { reason?: unknown }).reason;
  if (reason instanceof Error) throw reason;
  if (reason !== undefined) throw new AbortError(String(reason));
  throw new AbortError("searchAllMessages aborted");
}

/**
 * Async-iterable that yields every `SearchHit` for the given query
 * across every page. Caller can break out of `for await` early at any
 * time; the next page is only requested when the previous one is
 * exhausted.
 *
 * Example:
 *   for await (const hit of searchAllMessages(sdk, { text: "alert" })) {
 *     console.log(hit.id, hit.text);
 *   }
 *
 * With cancellation + cap:
 *   const ac = new AbortController();
 *   setTimeout(() => ac.abort(), 5_000);
 *   for await (const hit of searchAllMessages(sdk, { text: "x" }, {
 *     signal: ac.signal,
 *     maxResults: 1_000,
 *   })) { ... }
 */
export async function* searchAllMessages(
  client: SearchAllClient,
  request: SearchMessagesRequest,
  options: SearchAllOptions = {},
): AsyncGenerator<SearchHit, void, void> {
  const { signal, maxResults, onPage } = options;
  const HARD_PAGE_CAP = options.maxPages ?? 10_000;

  const seen = new Set<string>();
  const limit = request.limit ?? 10;
  let cursor: number | undefined = request.beforeTs;
  let prevFirstId: string | undefined;
  let pageIndex = 0;
  let yielded = 0;

  while (true) {
    throwIfAborted(signal);
    if (pageIndex >= HARD_PAGE_CAP) {
      throw new Error(
        `searchAllMessages: exceeded ${HARD_PAGE_CAP} pages — refusing to continue (possible server loop)`,
      );
    }

    const pageReq: SearchMessagesRequest = cursor === undefined
      ? request
      : { ...request, beforeTs: cursor };

    const page = await client.messages.searchMessages(pageReq);
    pageIndex++;
    throwIfAborted(signal);

    const content = page.result?.content ?? [];

    if (content.length === 0) {
      return;
    }

    const firstId = content[0]?.id;
    if (firstId !== undefined && firstId === prevFirstId) {
      // Server returned the exact same page again — bail to avoid loop.
      return;
    }
    prevFirstId = firstId;

    // Pass 1: compute minTs (defensive against missing timestampMilli)
    // and count new ids without yielding yet, so `onPage` sees accurate
    // counts.
    let newInPage = 0;
    let minTs = Number.POSITIVE_INFINITY;
    for (const hit of content) {
      const ts = typeof hit.timestampMilli === "number" && isFinite(hit.timestampMilli)
        ? hit.timestampMilli
        : undefined;
      if (ts !== undefined && ts < minTs) minTs = ts;
      if (typeof hit.id === "string" && !seen.has(hit.id)) newInPage++;
    }

    if (onPage) {
      await onPage(page, { pageIndex, newInPage, yielded });
      throwIfAborted(signal);
    }

    // Pass 2: yield the new hits. We yield in the order returned by
    // the server (newest first by convention).
    for (const hit of content) {
      if (typeof hit.id !== "string" || seen.has(hit.id)) continue;
      seen.add(hit.id);
      yielded++;
      yield hit;
      throwIfAborted(signal);
      if (maxResults !== undefined && yielded >= maxResults) {
        return;
      }
    }

    // If the page brought zero new ids after dedupe, we're spinning.
    if (newInPage === 0) {
      return;
    }

    // hasMore is the canonical stop signal — combined with a short
    // page that's a safe terminator.
    if (page.result.hasMore === false && content.length < limit) {
      return;
    }
    // Server contradiction: claims more but returned no hits at all.
    // Already handled by `content.length === 0` above, but guard the
    // inverse just in case.
    if (page.result.hasMore === false && newInPage === 0) {
      return;
    }

    if (!isFinite(minTs)) {
      // No usable timestamps on this page — cursor can't advance.
      return;
    }
    // Step past the current page's earliest timestamp. `-1` is safe
    // because timestampMilli is server-stored at second precision.
    const nextCursor = minTs - 1;
    if (cursor !== undefined && nextCursor >= cursor) {
      // Cursor failed to advance — bail.
      return;
    }
    cursor = nextCursor;
  }
}
