// Hand-written extension. NOT regenerated by Speakeasy — safe to edit.

import type { RequestOptions } from "../lib/sdks.js";
import type { Message } from "../models/message.js";
import type { MessageRef } from "../models/message-ref.js";
import type {
  FetchMessageRequest,
  FetchThreadRepliesRequest,
  SendReplyRequest,
} from "../models/operations/index.js";

export type ThreadContextOptions = RequestOptions;
export type ReplyToThreadOptions = RequestOptions;

export interface ThreadContextClient {
  messages: {
    fetchMessage(
      request: FetchMessageRequest,
      options?: RequestOptions,
    ): Promise<Message>;
    fetchThreadReplies(
      request: FetchThreadRepliesRequest,
      options?: RequestOptions,
    ): Promise<{ result: Message[] }>;
  };
}

export interface ReplyToThreadClient {
  messages: {
    sendReply(
      request: SendReplyRequest,
      options?: RequestOptions,
    ): Promise<MessageRef>;
  };
}

export interface ThreadContextRequest {
  channelId: string;
  messageId: string;
  replyLimit?: number | undefined;
}

export type ReplyToThreadRequest =
  & Omit<SendReplyRequest, "channel" | "channelId" | "messageId">
  & {
    channelId: string;
    messageId: string;
  };

export interface ThreadContextMessage {
  id: string;
  channelId: string;
  author: string;
  text: string;
  timestamp: string;
  timestampMilli: number;
}

export interface ThreadContext {
  root: ThreadContextMessage;
  replies: ThreadContextMessage[];
  participants: string[];
  replyCount: number;
}

function requireNonBlank(value: string, name: string, helper: string): void {
  if (value.trim().length === 0) {
    throw new Error(`${helper}: ${name} is required`);
  }
}

function replyLimit(value: number | undefined): number | undefined {
  if (value === undefined) return undefined;
  if (!Number.isFinite(value) || value < 1) {
    throw new Error("getThreadContext: replyLimit must be a positive number");
  }
  return Math.floor(value);
}

function compactMessage(message: Message): ThreadContextMessage {
  return {
    id: message.id,
    channelId: message.channelId,
    author: message.author,
    text: message.text,
    timestamp: message.timestamp.toISOString(),
    timestampMilli: message.timestampMilli,
  };
}

function participantsFor(root: Message, replies: Message[]): string[] {
  const seen = new Set<string>();
  const participants: string[] = [];
  for (const message of [root, ...replies]) {
    if (message.author.trim().length === 0 || seen.has(message.author)) continue;
    seen.add(message.author);
    participants.push(message.author);
  }
  return participants;
}

/**
 * Fetch a thread root and one compact page of replies. This helper does
 * not summarize or transform message text; it only removes bulky fields
 * and extracts participant ids.
 */
export async function getThreadContext(
  client: ThreadContextClient,
  request: ThreadContextRequest,
  options?: ThreadContextOptions,
): Promise<ThreadContext> {
  requireNonBlank(request.channelId, "channelId", "getThreadContext");
  requireNonBlank(request.messageId, "messageId", "getThreadContext");

  const limit = replyLimit(request.replyLimit);
  const repliesRequest: FetchThreadRepliesRequest = {
    channelId: request.channelId,
    rootMessageId: request.messageId,
  };
  if (limit !== undefined) {
    repliesRequest.limit = limit;
  }

  const [root, repliesPage] = await Promise.all([
    client.messages.fetchMessage({
      channelId: request.channelId,
      messageId: request.messageId,
    }, options),
    client.messages.fetchThreadReplies(repliesRequest, options),
  ]);
  const replies = limit === undefined
    ? repliesPage.result
    : repliesPage.result.slice(0, limit);

  return {
    root: compactMessage(root),
    replies: replies.map(compactMessage),
    participants: participantsFor(root, replies),
    replyCount: root.threadRootInfo?.replyCount ?? replies.length,
  };
}

/**
 * Safer thread reply facade: callers must provide explicit channel and
 * root message ids, and blank reply bodies are rejected before dispatch.
 */
export async function replyToThread(
  client: ReplyToThreadClient,
  request: ReplyToThreadRequest,
  options?: ReplyToThreadOptions,
): Promise<MessageRef> {
  requireNonBlank(request.channelId, "channelId", "replyToThread");
  requireNonBlank(request.messageId, "messageId", "replyToThread");
  requireNonBlank(request.text, "text", "replyToThread");

  return client.messages.sendReply(request, options);
}
