// Hand-written extension. NOT regenerated by Speakeasy - safe to edit.

import { createHash, createHmac, timingSafeEqual, type BinaryLike } from "node:crypto";

export type WriteRiskLevel = "low" | "medium" | "high";
export type ConfirmationSecret = BinaryLike;

export interface WriteActionTarget {
  kind?: string;
  id?: string;
  name?: string;
}

export interface WriteAction {
  type?: string;
  actionType?: string;
  targetKind?: string;
  targetId?: string;
  targetName?: string;
  target?: WriteActionTarget;
  text?: string;
  riskLevel?: WriteRiskLevel;
}

export interface WritePreview {
  actionType: string;
  targetKind: string;
  targetId?: string;
  targetName?: string;
  textExcerpt: string;
  /** SHA-256 hex digest of the full message text; binds text beyond the excerpt. */
  textSha256: string;
  riskLevel: WriteRiskLevel;
}

const TOKEN_PREFIX = "pumble-write-plan-v1";
const TEXT_EXCERPT_MAX_LENGTH = 160;
const RISK_LEVELS = new Set<string>(["low", "medium", "high"]);

/**
 * Build a local preview for a pending write. The preview is intentionally
 * detached from API state: callers decide where, whether, and how long to keep it.
 */
export function createWritePreview(action: WriteAction): WritePreview {
  const actionType = firstNonBlank(action.actionType, action.type);
  if (actionType === undefined) {
    throw new TypeError("createWritePreview: action type is required");
  }

  const targetKind = firstNonBlank(action.targetKind, action.target?.kind);
  if (targetKind === undefined) {
    throw new TypeError("createWritePreview: target kind is required");
  }

  const targetId = firstNonBlank(action.targetId, action.target?.id);
  const targetName = firstNonBlank(action.targetName, action.target?.name);
  if (targetId === undefined && targetName === undefined) {
    throw new TypeError("createWritePreview: target id or target name is required");
  }

  return {
    actionType,
    targetKind,
    ...(targetId !== undefined ? { targetId } : {}),
    ...(targetName !== undefined ? { targetName } : {}),
    textExcerpt: excerptText(action.text),
    textSha256: hashText(action.text),
    riskLevel: normalizeRiskLevel(action.riskLevel, actionType),
  };
}

export function createConfirmationToken(
  preview: WritePreview,
  secretOrSalt: ConfirmationSecret,
): string {
  requireSecret(secretOrSalt);
  const digest = createHmac("sha256", secretOrSalt)
    .update(canonicalJson(preview))
    .digest("base64url");
  return `${TOKEN_PREFIX}.${digest}`;
}

export function verifyConfirmationToken(
  preview: WritePreview,
  token: string,
  secretOrSalt: ConfirmationSecret,
): boolean {
  if (typeof token !== "string" || !token.startsWith(`${TOKEN_PREFIX}.`)) {
    return false;
  }
  const expected = createConfirmationToken(preview, secretOrSalt);
  return timingSafeStringEqual(token, expected);
}

function firstNonBlank(...values: Array<string | undefined>): string | undefined {
  for (const value of values) {
    if (typeof value !== "string") continue;
    const trimmed = value.trim();
    if (trimmed.length > 0) return trimmed;
  }
  return undefined;
}

function excerptText(text: string | undefined): string {
  if (typeof text !== "string") return "";
  const redacted = redactSensitiveText(text.replace(/\s+/g, " ").trim());
  if (redacted.length <= TEXT_EXCERPT_MAX_LENGTH) return redacted;
  return `${redacted.slice(0, TEXT_EXCERPT_MAX_LENGTH - 3).trimEnd()}...`;
}

function hashText(text: string | undefined): string {
  return createHash("sha256").update(text ?? "", "utf8").digest("hex");
}

function redactSensitiveText(text: string): string {
  return text
    .replace(/\bpmb_[A-Za-z0-9_-]+\b/g, "[redacted]")
    .replace(/\b(Bearer|Basic)\s+[A-Za-z0-9._~+/=-]+/gi, "$1 [redacted]")
    .replace(
      /\b(api[-_ ]?key|access[-_ ]?token|refresh[-_ ]?token|token|secret|password)\s*[:=]\s*(?:"[^"]*"|'[^']*'|[^\s,;]+)/gi,
      "$1=[redacted]",
    );
}

function normalizeRiskLevel(value: WriteRiskLevel | undefined, actionType: string): WriteRiskLevel {
  if (value === undefined) return inferRiskLevel(actionType);
  if (!RISK_LEVELS.has(value)) {
    throw new TypeError(`createWritePreview: unsupported risk level ${value}`);
  }
  return value;
}

function inferRiskLevel(actionType: string): WriteRiskLevel {
  if (/(delete|remove|revoke|archive|deactivate|cancel)/i.test(actionType)) {
    return "high";
  }
  if (/(send|post|reply|create|update|edit|invite|set|clear)/i.test(actionType)) {
    return "medium";
  }
  return "low";
}

function requireSecret(secret: ConfirmationSecret): void {
  if (typeof secret === "string") {
    if (secret.length === 0) {
      throw new TypeError("createConfirmationToken: secretOrSalt must be non-empty");
    }
    return;
  }
  if (secret.byteLength === 0) {
    throw new TypeError("createConfirmationToken: secretOrSalt must be non-empty");
  }
}

function canonicalJson(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalJson(item)).join(",")}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, entryValue]) => entryValue !== undefined)
    .sort(([left], [right]) => left.localeCompare(right));
  return `{${entries
    .map(([key, entryValue]) => `${JSON.stringify(key)}:${canonicalJson(entryValue)}`)
    .join(",")}}`;
}

function timingSafeStringEqual(actual: string, expected: string): boolean {
  const actualBuffer = Buffer.from(actual);
  const expectedBuffer = Buffer.from(expected);
  return actualBuffer.length === expectedBuffer.length && timingSafeEqual(actualBuffer, expectedBuffer);
}
