/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { PumbleSDKCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$channelsAddUsersToChannel } from "./tools/channels-add-users-to-channel.js";
import { tool$channelsCreateChannel } from "./tools/channels-create-channel.js";
import { tool$channelsGetChannel } from "./tools/channels-get-channel.js";
import { tool$channelsListChannels } from "./tools/channels-list-channels.js";
import { tool$channelsRemoveUserFromChannel } from "./tools/channels-remove-user-from-channel.js";
import { tool$messagesAddReaction } from "./tools/messages-add-reaction.js";
import { tool$messagesDeleteMessage } from "./tools/messages-delete-message.js";
import { tool$messagesDmGroup } from "./tools/messages-dm-group.js";
import { tool$messagesDmUser } from "./tools/messages-dm-user.js";
import { tool$messagesEditMessage } from "./tools/messages-edit-message.js";
import { tool$messagesFetchMessage } from "./tools/messages-fetch-message.js";
import { tool$messagesFetchThreadReplies } from "./tools/messages-fetch-thread-replies.js";
import { tool$messagesListMessages } from "./tools/messages-list-messages.js";
import { tool$messagesRemoveReaction } from "./tools/messages-remove-reaction.js";
import { tool$messagesSearchMessages } from "./tools/messages-search-messages.js";
import { tool$messagesSendMessage } from "./tools/messages-send-message.js";
import { tool$messagesSendReply } from "./tools/messages-send-reply.js";
import { tool$scheduledMessagesCreateScheduledMessage } from "./tools/scheduled-messages-create-scheduled-message.js";
import { tool$scheduledMessagesDeleteScheduledMessage } from "./tools/scheduled-messages-delete-scheduled-message.js";
import { tool$scheduledMessagesEditScheduledMessage } from "./tools/scheduled-messages-edit-scheduled-message.js";
import { tool$scheduledMessagesFetchScheduledMessage } from "./tools/scheduled-messages-fetch-scheduled-message.js";
import { tool$scheduledMessagesFetchScheduledMessages } from "./tools/scheduled-messages-fetch-scheduled-messages.js";
import { tool$usersCustomStatus } from "./tools/users-custom-status.js";
import { tool$usersListUserGroups } from "./tools/users-list-user-groups.js";
import { tool$usersListUsers } from "./tools/users-list-users.js";
import { tool$usersMyInfo } from "./tools/users-my-info.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  apiKeyAuth?: SDKOptions["apiKeyAuth"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "PumbleSDK",
    version: "0.3.22",
  });

  const client = new PumbleSDKCore({
    apiKeyAuth: deps.apiKeyAuth,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$channelsListChannels);
  tool(tool$channelsGetChannel);
  tool(tool$channelsCreateChannel);
  tool(tool$channelsAddUsersToChannel);
  tool(tool$channelsRemoveUserFromChannel);
  tool(tool$messagesSendMessage);
  tool(tool$messagesSendReply);
  tool(tool$messagesDmUser);
  tool(tool$messagesDmGroup);
  tool(tool$messagesFetchMessage);
  tool(tool$messagesFetchThreadReplies);
  tool(tool$messagesSearchMessages);
  tool(tool$messagesDeleteMessage);
  tool(tool$messagesListMessages);
  tool(tool$messagesAddReaction);
  tool(tool$messagesRemoveReaction);
  tool(tool$messagesEditMessage);
  tool(tool$scheduledMessagesCreateScheduledMessage);
  tool(tool$scheduledMessagesFetchScheduledMessages);
  tool(tool$scheduledMessagesFetchScheduledMessage);
  tool(tool$scheduledMessagesEditScheduledMessage);
  tool(tool$scheduledMessagesDeleteScheduledMessage);
  tool(tool$usersListUsers);
  tool(tool$usersListUserGroups);
  tool(tool$usersMyInfo);
  tool(tool$usersCustomStatus);

  return server;
}
