/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesEditMessage } from "../../funcs/messages-edit-message.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EditMessageRequest$inboundSchema,
};

export const tool$messagesEditMessage: ToolDefinition<typeof args> = {
  name: "messages-edit-message",
  description: `Edit a message`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesEditMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
