/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesDmGroup } from "../../funcs/messages-dm-group.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DmGroupRequest$inboundSchema,
};

export const tool$messagesDmGroup: ToolDefinition<typeof args> = {
  name: "messages-dm-group",
  description: `Send a direct message to a group of users

Opens (or reuses) a multi-party DM channel and posts a message.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesDmGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
