/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesSendReply } from "../../funcs/messages-send-reply.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SendReplyRequest$inboundSchema,
};

export const tool$messagesSendReply: ToolDefinition<typeof args> = {
  name: "messages-send-reply",
  description: `Reply to a message in a channel (thread)

Posts \`text\` as a reply in the thread rooted at \`messageId\`. Provide
**either** \`channelId\` (preferred) **or** \`channel\` (by name).
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesSendReply(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
