/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesFetchThreadReplies } from "../../funcs/messages-fetch-thread-replies.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FetchThreadRepliesRequest$inboundSchema,
};

export const tool$messagesFetchThreadReplies: ToolDefinition<typeof args> = {
  name: "messages-fetch-thread-replies",
  description: `Fetch the replies of a thread

Returns the replies posted in the thread rooted at \`rootMessageId\`,
as a flat array. Supports cursor pagination via the last reply's \`id\`.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await messagesFetchThreadReplies(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
