/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledMessagesFetchScheduledMessages } from "../../funcs/scheduled-messages-fetch-scheduled-messages.js";
import * as operations from "../../models/operations/index.js";
import * as types from "../../types/primitives.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: types.optional(
    operations.FetchScheduledMessagesRequest$inboundSchema,
  ),
};

export const tool$scheduledMessagesFetchScheduledMessages: ToolDefinition<
  typeof args
> = {
  name: "scheduled-messages-fetch-scheduled-messages",
  description: `Fetch a list of scheduled messages

Returns scheduled messages for the workspace (optionally filtered to
a single channel). Cursor pagination uses the last scheduled
message's \`id\`.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await scheduledMessagesFetchScheduledMessages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
