/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledMessagesCreateScheduledMessage } from "../../funcs/scheduled-messages-create-scheduled-message.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateScheduledMessageRequest$inboundSchema,
};

export const tool$scheduledMessagesCreateScheduledMessage: ToolDefinition<
  typeof args
> = {
  name: "scheduled-messages-create-scheduled-message",
  description: `Create a scheduled (future) message`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await scheduledMessagesCreateScheduledMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
