/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateScheduledMessageRequest = {
  channelId: string;
  text: string;
  /**
   * Delivery moment (epoch ms). Must be in the future.
   */
  sendAt: number;
  blocks?: Array<models.MessageBlock> | undefined;
  /**
   * If set, the scheduled message will be sent as a thread reply.
   */
  threadRootId?: string | undefined;
  alsoSendToChannel?: boolean | undefined;
  recurrence?: models.Recurrence | undefined;
};

/** @internal */
export const CreateScheduledMessageRequest$inboundSchema: z.ZodType<
  CreateScheduledMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channelId: types.string(),
  text: types.string(),
  sendAt: types.number(),
  blocks: types.optional(z.array(models.MessageBlock$inboundSchema)),
  threadRootId: types.optional(types.string()),
  alsoSendToChannel: types.optional(types.boolean()),
  recurrence: types.optional(models.Recurrence$inboundSchema),
});
/** @internal */
export type CreateScheduledMessageRequest$Outbound = {
  channelId: string;
  text: string;
  sendAt: number;
  blocks?: Array<models.MessageBlock$Outbound> | undefined;
  threadRootId?: string | undefined;
  alsoSendToChannel?: boolean | undefined;
  recurrence?: models.Recurrence$Outbound | undefined;
};

/** @internal */
export const CreateScheduledMessageRequest$outboundSchema: z.ZodType<
  CreateScheduledMessageRequest$Outbound,
  z.ZodTypeDef,
  CreateScheduledMessageRequest
> = z.object({
  channelId: z.string().min(1),
  text: z.string().min(1),
  sendAt: z.number().int().min(1),
  blocks: z.array(models.MessageBlock$outboundSchema).optional(),
  threadRootId: z.string().optional(),
  alsoSendToChannel: z.boolean().optional(),
  recurrence: models.Recurrence$outboundSchema.optional(),
});

export function createScheduledMessageRequestToJSON(
  createScheduledMessageRequest: CreateScheduledMessageRequest,
): string {
  return JSON.stringify(
    CreateScheduledMessageRequest$outboundSchema.parse(
      createScheduledMessageRequest,
    ),
  );
}
export function createScheduledMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateScheduledMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateScheduledMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateScheduledMessageRequest' from JSON`,
  );
}
