/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DmUserRequest = {
  userId: string;
  text: string;
  asBot?: boolean | undefined;
};

/** @internal */
export const DmUserRequest$inboundSchema: z.ZodType<
  DmUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  userId: types.string(),
  text: types.string(),
  asBot: types.optional(types.boolean()),
});
/** @internal */
export type DmUserRequest$Outbound = {
  userId: string;
  text: string;
  asBot?: boolean | undefined;
};

/** @internal */
export const DmUserRequest$outboundSchema: z.ZodType<
  DmUserRequest$Outbound,
  z.ZodTypeDef,
  DmUserRequest
> = z.object({
  userId: z.string(),
  text: z.string(),
  asBot: z.boolean().optional(),
});

export function dmUserRequestToJSON(dmUserRequest: DmUserRequest): string {
  return JSON.stringify(DmUserRequest$outboundSchema.parse(dmUserRequest));
}
export function dmUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<DmUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DmUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DmUserRequest' from JSON`,
  );
}
