/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type FetchScheduledMessagesRequest = {
  channelId?: string | undefined;
  cursor?: string | undefined;
  limit?: number | undefined;
};

export type FetchScheduledMessagesResponse = {
  result: models.ScheduledMessageList;
};

/** @internal */
export const FetchScheduledMessagesRequest$inboundSchema: z.ZodType<
  FetchScheduledMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channelId: types.optional(types.string()),
  cursor: types.optional(types.string()),
  limit: types.number().default(100),
});
/** @internal */
export type FetchScheduledMessagesRequest$Outbound = {
  channelId?: string | undefined;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const FetchScheduledMessagesRequest$outboundSchema: z.ZodType<
  FetchScheduledMessagesRequest$Outbound,
  z.ZodTypeDef,
  FetchScheduledMessagesRequest
> = z.object({
  channelId: z.string().optional(),
  cursor: z.string().optional(),
  limit: z.number().int().default(100),
});

export function fetchScheduledMessagesRequestToJSON(
  fetchScheduledMessagesRequest: FetchScheduledMessagesRequest,
): string {
  return JSON.stringify(
    FetchScheduledMessagesRequest$outboundSchema.parse(
      fetchScheduledMessagesRequest,
    ),
  );
}
export function fetchScheduledMessagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchScheduledMessagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchScheduledMessagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchScheduledMessagesRequest' from JSON`,
  );
}

/** @internal */
export const FetchScheduledMessagesResponse$inboundSchema: z.ZodType<
  FetchScheduledMessagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.ScheduledMessageList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type FetchScheduledMessagesResponse$Outbound = {
  Result: models.ScheduledMessageList$Outbound;
};

/** @internal */
export const FetchScheduledMessagesResponse$outboundSchema: z.ZodType<
  FetchScheduledMessagesResponse$Outbound,
  z.ZodTypeDef,
  FetchScheduledMessagesResponse
> = z.object({
  result: models.ScheduledMessageList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function fetchScheduledMessagesResponseToJSON(
  fetchScheduledMessagesResponse: FetchScheduledMessagesResponse,
): string {
  return JSON.stringify(
    FetchScheduledMessagesResponse$outboundSchema.parse(
      fetchScheduledMessagesResponse,
    ),
  );
}
export function fetchScheduledMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchScheduledMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchScheduledMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchScheduledMessagesResponse' from JSON`,
  );
}
