/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FetchMessageRequest = {
  messageId: string;
  channelId?: string | undefined;
  channel?: string | undefined;
};

/** @internal */
export const FetchMessageRequest$inboundSchema: z.ZodType<
  FetchMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: types.string(),
  channelId: types.optional(types.string()),
  channel: types.optional(types.string()),
});
/** @internal */
export type FetchMessageRequest$Outbound = {
  messageId: string;
  channelId?: string | undefined;
  channel?: string | undefined;
};

/** @internal */
export const FetchMessageRequest$outboundSchema: z.ZodType<
  FetchMessageRequest$Outbound,
  z.ZodTypeDef,
  FetchMessageRequest
> = z.object({
  messageId: z.string(),
  channelId: z.string().optional(),
  channel: z.string().optional(),
});

export function fetchMessageRequestToJSON(
  fetchMessageRequest: FetchMessageRequest,
): string {
  return JSON.stringify(
    FetchMessageRequest$outboundSchema.parse(fetchMessageRequest),
  );
}
export function fetchMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchMessageRequest' from JSON`,
  );
}
