/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SendMessageRequest = {
  channelId?: string | undefined;
  /**
   * Channel name; ignored if `channelId` is provided.
   */
  channel?: string | undefined;
  text: string;
  /**
   * If set, post as a reply in this thread.
   */
  threadRootId?: string | undefined;
  /**
   * If true, the message is authored by the addon's bot identity instead of the API-key owner.
   */
  asBot?: boolean | undefined;
  /**
   * Pumble rich-text blocks. If provided, takes precedence over `text` for rendering.
   */
  blocks?: Array<models.MessageBlock> | undefined;
};

/** @internal */
export const SendMessageRequest$inboundSchema: z.ZodType<
  SendMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channelId: types.optional(types.string()),
  channel: types.optional(types.string()),
  text: types.string(),
  threadRootId: types.optional(types.string()),
  asBot: types.optional(types.boolean()),
  blocks: types.optional(z.array(models.MessageBlock$inboundSchema)),
});
/** @internal */
export type SendMessageRequest$Outbound = {
  channelId?: string | undefined;
  channel?: string | undefined;
  text: string;
  threadRootId?: string | undefined;
  asBot?: boolean | undefined;
  blocks?: Array<models.MessageBlock$Outbound> | undefined;
};

/** @internal */
export const SendMessageRequest$outboundSchema: z.ZodType<
  SendMessageRequest$Outbound,
  z.ZodTypeDef,
  SendMessageRequest
> = z.object({
  channelId: z.string().optional(),
  channel: z.string().optional(),
  text: z.string(),
  threadRootId: z.string().optional(),
  asBot: z.boolean().optional(),
  blocks: z.array(models.MessageBlock$outboundSchema).optional(),
});

export function sendMessageRequestToJSON(
  sendMessageRequest: SendMessageRequest,
): string {
  return JSON.stringify(
    SendMessageRequest$outboundSchema.parse(sendMessageRequest),
  );
}
export function sendMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageRequest' from JSON`,
  );
}
