/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SendReplyRequest = {
  channelId?: string | undefined;
  channel?: string | undefined;
  /**
   * ID of the message to reply to (the thread root).
   */
  messageId: string;
  text: string;
  /**
   * If true, also broadcast the reply to the parent channel.
   */
  alsoSendToChannel?: boolean | undefined;
  asBot?: boolean | undefined;
};

/** @internal */
export const SendReplyRequest$inboundSchema: z.ZodType<
  SendReplyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channelId: types.optional(types.string()),
  channel: types.optional(types.string()),
  messageId: types.string(),
  text: types.string(),
  alsoSendToChannel: types.optional(types.boolean()),
  asBot: types.optional(types.boolean()),
});
/** @internal */
export type SendReplyRequest$Outbound = {
  channelId?: string | undefined;
  channel?: string | undefined;
  messageId: string;
  text: string;
  alsoSendToChannel?: boolean | undefined;
  asBot?: boolean | undefined;
};

/** @internal */
export const SendReplyRequest$outboundSchema: z.ZodType<
  SendReplyRequest$Outbound,
  z.ZodTypeDef,
  SendReplyRequest
> = z.object({
  channelId: z.string().optional(),
  channel: z.string().optional(),
  messageId: z.string(),
  text: z.string(),
  alsoSendToChannel: z.boolean().optional(),
  asBot: z.boolean().optional(),
});

export function sendReplyRequestToJSON(
  sendReplyRequest: SendReplyRequest,
): string {
  return JSON.stringify(
    SendReplyRequest$outboundSchema.parse(sendReplyRequest),
  );
}
export function sendReplyRequestFromJSON(
  jsonString: string,
): SafeParseResult<SendReplyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendReplyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendReplyRequest' from JSON`,
  );
}
