/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { channelsAddUsersToChannel } from "../funcs/channels-add-users-to-channel.js";
import { channelsCreateChannel } from "../funcs/channels-create-channel.js";
import { channelsGetChannel } from "../funcs/channels-get-channel.js";
import { channelsListChannels } from "../funcs/channels-list-channels.js";
import { channelsRemoveUserFromChannel } from "../funcs/channels-remove-user-from-channel.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Channels extends ClientSDK {
  /**
   * List all channels
   *
   * @remarks
   * Returns every channel visible to the API key.
   */
  async listChannels(
    options?: RequestOptions,
  ): Promise<Array<models.ChannelListEntry>> {
    return unwrapAsync(channelsListChannels(
      this,
      options,
    ));
  }

  /**
   * Get channel details by ID or name
   *
   * @remarks
   * Provide **either** `channelId` (preferred) **or** `channel` (by name).
   * The response wraps the channel in `{ channel: ... }` (mirroring
   * `listChannels`), without the `pinnedMessages` / `users` fields.
   */
  async getChannel(
    request?: operations.GetChannelRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetChannelResponse> {
    return unwrapAsync(channelsGetChannel(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new channel
   *
   * @remarks
   * Creates a new public or private channel. The caller becomes the
   * channel creator and is added as a member.
   */
  async createChannel(
    request: operations.CreateChannelRequest,
    options?: RequestOptions,
  ): Promise<models.ChannelRef> {
    return unwrapAsync(channelsCreateChannel(
      this,
      request,
      options,
    ));
  }

  /**
   * Add users to a channel
   */
  async addUsersToChannel(
    request: operations.AddUsersToChannelRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(channelsAddUsersToChannel(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a user from a channel
   */
  async removeUserFromChannel(
    request: operations.RemoveUserFromChannelRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(channelsRemoveUserFromChannel(
      this,
      request,
      options,
    ));
  }
}
