/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e62ad114dd2f
 */

import { ClientSDK } from "../lib/sdks.js";
import { Channels } from "./channels.js";
import { Messages } from "./messages.js";
import { ScheduledMessages } from "./scheduled-messages.js";
import { Users } from "./users.js";

export class PumbleSDK extends ClientSDK {
  private _channels?: Channels;
  get channels(): Channels {
    return (this._channels ??= new Channels(this._options));
  }

  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _scheduledMessages?: ScheduledMessages;
  get scheduledMessages(): ScheduledMessages {
    return (this._scheduledMessages ??= new ScheduledMessages(this._options));
  }

  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }
}
