/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 79dcf0a1dfaa
 */

import { usersCustomStatus } from "../funcs/users-custom-status.js";
import { usersListUserGroups } from "../funcs/users-list-user-groups.js";
import { usersListUsers } from "../funcs/users-list-users.js";
import { usersMyInfo } from "../funcs/users-my-info.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Users extends ClientSDK {
  /**
   * List all workspace users
   *
   * @remarks
   * Returns every user in the workspace as a flat array.
   */
  async listUsers(
    options?: RequestOptions,
  ): Promise<Array<models.User>> {
    return unwrapAsync(usersListUsers(
      this,
      options,
    ));
  }

  /**
   * List workspace user groups
   */
  async listUserGroups(
    options?: RequestOptions,
  ): Promise<Array<models.UserGroup>> {
    return unwrapAsync(usersListUserGroups(
      this,
      options,
    ));
  }

  /**
   * Get info about the authenticated user
   *
   * @remarks
   * Returns the user record for whichever account owns the API key.
   */
  async myInfo(
    options?: RequestOptions,
  ): Promise<models.User> {
    return unwrapAsync(usersMyInfo(
      this,
      options,
    ));
  }

  /**
   * Update the custom status of the authenticated user
   *
   * @remarks
   * Sets or clears the user's custom status. **Both** `code` and
   * `expiresAt` are required server-side. Pass an `expiresAt` far in the
   * future for a "don't auto-clear" effect; pass a past timestamp to
   * immediately clear.
   */
  async customStatus(
    request: operations.CustomStatusRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersCustomStatus(
      this,
      request,
      options,
    ));
  }
}
