/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the pumble-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx channelsListChannels.example.ts
 */

import { PumbleSDK } from "pumble-sdk";

const pumbleSDK = new PumbleSDK({
  apiKeyAuth: process.env["PUMBLESDK_API_KEY_AUTH"] ?? "",
});

async function main() {
  const result = await pumbleSDK.channels.listChannels();

  console.log(result);
}

main().catch(console.error);
