/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type AddUsersToChannelRequest = {
  channelId: string;
  userIds: Array<string>;
};

/** @internal */
export const AddUsersToChannelRequest$inboundSchema: z.ZodType<
  AddUsersToChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channelId: types.string(),
  userIds: z.array(types.string()),
});
/** @internal */
export type AddUsersToChannelRequest$Outbound = {
  channelId: string;
  userIds: Array<string>;
};

/** @internal */
export const AddUsersToChannelRequest$outboundSchema: z.ZodType<
  AddUsersToChannelRequest$Outbound,
  z.ZodTypeDef,
  AddUsersToChannelRequest
> = z.object({
  channelId: z.string(),
  userIds: z.array(z.string()),
});

export function addUsersToChannelRequestToJSON(
  addUsersToChannelRequest: AddUsersToChannelRequest,
): string {
  return JSON.stringify(
    AddUsersToChannelRequest$outboundSchema.parse(addUsersToChannelRequest),
  );
}
export function addUsersToChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddUsersToChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddUsersToChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddUsersToChannelRequest' from JSON`,
  );
}
