/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2920d956720e
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type AddReactionRequest = {
  messageId: string;
  channelId?: string | undefined;
  /**
   * Emoji code in `:emoji_name:` form (e.g. `:+1:`).
   */
  reaction: string;
  skinTone?: number | undefined;
};

/**
 * Reaction added.
 */
export type AddReactionResponse = {
  status?: string | undefined;
};

/** @internal */
export const AddReactionRequest$inboundSchema: z.ZodType<
  AddReactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: types.string(),
  channelId: types.optional(types.string()),
  reaction: types.string(),
  skinTone: types.optional(types.number()),
});
/** @internal */
export type AddReactionRequest$Outbound = {
  messageId: string;
  channelId?: string | undefined;
  reaction: string;
  skinTone?: number | undefined;
};

/** @internal */
export const AddReactionRequest$outboundSchema: z.ZodType<
  AddReactionRequest$Outbound,
  z.ZodTypeDef,
  AddReactionRequest
> = z.object({
  messageId: z.string(),
  channelId: z.string().optional(),
  reaction: z.string(),
  skinTone: z.number().int().optional(),
});

export function addReactionRequestToJSON(
  addReactionRequest: AddReactionRequest,
): string {
  return JSON.stringify(
    AddReactionRequest$outboundSchema.parse(addReactionRequest),
  );
}
export function addReactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddReactionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddReactionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddReactionRequest' from JSON`,
  );
}

/** @internal */
export const AddReactionResponse$inboundSchema: z.ZodType<
  AddReactionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: types.optional(types.string()),
});
/** @internal */
export type AddReactionResponse$Outbound = {
  status?: string | undefined;
};

/** @internal */
export const AddReactionResponse$outboundSchema: z.ZodType<
  AddReactionResponse$Outbound,
  z.ZodTypeDef,
  AddReactionResponse
> = z.object({
  status: z.string().optional(),
});

export function addReactionResponseToJSON(
  addReactionResponse: AddReactionResponse,
): string {
  return JSON.stringify(
    AddReactionResponse$outboundSchema.parse(addReactionResponse),
  );
}
export function addReactionResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddReactionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddReactionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddReactionResponse' from JSON`,
  );
}
