/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateChannelRequest = {
  /**
   * Channel name. Pumble normalizes this server-side
   *
   * @remarks
   * (lower-cases, replaces spaces with `-`).
   */
  name: string;
  /**
   * Visibility of a channel.
   */
  type: models.ChannelType;
  /**
   * Optional channel description.
   */
  description?: string | undefined;
};

/** @internal */
export const CreateChannelRequest$inboundSchema: z.ZodType<
  CreateChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: types.string(),
  type: models.ChannelType$inboundSchema,
  description: types.optional(types.string()),
});
/** @internal */
export type CreateChannelRequest$Outbound = {
  name: string;
  type: string;
  description?: string | undefined;
};

/** @internal */
export const CreateChannelRequest$outboundSchema: z.ZodType<
  CreateChannelRequest$Outbound,
  z.ZodTypeDef,
  CreateChannelRequest
> = z.object({
  name: z.string(),
  type: models.ChannelType$outboundSchema,
  description: z.string().optional(),
});

export function createChannelRequestToJSON(
  createChannelRequest: CreateChannelRequest,
): string {
  return JSON.stringify(
    CreateChannelRequest$outboundSchema.parse(createChannelRequest),
  );
}
export function createChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateChannelRequest' from JSON`,
  );
}
