/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 739d884d8c2f
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CustomStatusRequest = {
  /**
   * Emoji code in `:emoji_name:` form.
   */
  code: string;
  /**
   * Free-form status text.
   */
  status?: string | undefined;
  /**
   * Epoch-ms moment to clear the status (0 = never).
   */
  expiresAt: number;
};

/** @internal */
export const CustomStatusRequest$inboundSchema: z.ZodType<
  CustomStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: types.string(),
  status: types.optional(types.string()),
  expiresAt: types.number(),
});
/** @internal */
export type CustomStatusRequest$Outbound = {
  code: string;
  status?: string | undefined;
  expiresAt: number;
};

/** @internal */
export const CustomStatusRequest$outboundSchema: z.ZodType<
  CustomStatusRequest$Outbound,
  z.ZodTypeDef,
  CustomStatusRequest
> = z.object({
  code: z.string(),
  status: z.string().optional(),
  expiresAt: z.number().int(),
});

export function customStatusRequestToJSON(
  customStatusRequest: CustomStatusRequest,
): string {
  return JSON.stringify(
    CustomStatusRequest$outboundSchema.parse(customStatusRequest),
  );
}
export function customStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<CustomStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomStatusRequest' from JSON`,
  );
}
