/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f9ba3bc00801
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteScheduledMessageRequest = {
  scheduledMessageId: string;
};

/** @internal */
export const DeleteScheduledMessageRequest$inboundSchema: z.ZodType<
  DeleteScheduledMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  scheduledMessageId: types.string(),
});
/** @internal */
export type DeleteScheduledMessageRequest$Outbound = {
  scheduledMessageId: string;
};

/** @internal */
export const DeleteScheduledMessageRequest$outboundSchema: z.ZodType<
  DeleteScheduledMessageRequest$Outbound,
  z.ZodTypeDef,
  DeleteScheduledMessageRequest
> = z.object({
  scheduledMessageId: z.string(),
});

export function deleteScheduledMessageRequestToJSON(
  deleteScheduledMessageRequest: DeleteScheduledMessageRequest,
): string {
  return JSON.stringify(
    DeleteScheduledMessageRequest$outboundSchema.parse(
      deleteScheduledMessageRequest,
    ),
  );
}
export function deleteScheduledMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteScheduledMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteScheduledMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteScheduledMessageRequest' from JSON`,
  );
}
