/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aa9e3cbe8755
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteMessageRequest = {
  messageId: string;
  channelId?: string | undefined;
  channel?: string | undefined;
};

/** @internal */
export const DeleteMessageRequest$inboundSchema: z.ZodType<
  DeleteMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: types.string(),
  channelId: types.optional(types.string()),
  channel: types.optional(types.string()),
});
/** @internal */
export type DeleteMessageRequest$Outbound = {
  messageId: string;
  channelId?: string | undefined;
  channel?: string | undefined;
};

/** @internal */
export const DeleteMessageRequest$outboundSchema: z.ZodType<
  DeleteMessageRequest$Outbound,
  z.ZodTypeDef,
  DeleteMessageRequest
> = z.object({
  messageId: z.string(),
  channelId: z.string().optional(),
  channel: z.string().optional(),
});

export function deleteMessageRequestToJSON(
  deleteMessageRequest: DeleteMessageRequest,
): string {
  return JSON.stringify(
    DeleteMessageRequest$outboundSchema.parse(deleteMessageRequest),
  );
}
export function deleteMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteMessageRequest' from JSON`,
  );
}
