/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DmGroupRequest = {
  userIds: Array<string>;
  text: string;
  asBot?: boolean | undefined;
};

/** @internal */
export const DmGroupRequest$inboundSchema: z.ZodType<
  DmGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  userIds: z.array(types.string()),
  text: types.string(),
  asBot: types.optional(types.boolean()),
});
/** @internal */
export type DmGroupRequest$Outbound = {
  userIds: Array<string>;
  text: string;
  asBot?: boolean | undefined;
};

/** @internal */
export const DmGroupRequest$outboundSchema: z.ZodType<
  DmGroupRequest$Outbound,
  z.ZodTypeDef,
  DmGroupRequest
> = z.object({
  userIds: z.array(z.string()),
  text: z.string(),
  asBot: z.boolean().optional(),
});

export function dmGroupRequestToJSON(dmGroupRequest: DmGroupRequest): string {
  return JSON.stringify(DmGroupRequest$outboundSchema.parse(dmGroupRequest));
}
export function dmGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<DmGroupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DmGroupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DmGroupRequest' from JSON`,
  );
}
