/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type EditScheduledMessageRequest = {
  scheduledMessageId: string;
  channelId: string;
  text: string;
  /**
   * Delivery moment (epoch ms). Required even if unchanged.
   */
  sendAt: number;
  blocks?: Array<models.MessageBlock> | undefined;
  recurrence?: models.Recurrence | undefined;
};

/** @internal */
export const EditScheduledMessageRequest$inboundSchema: z.ZodType<
  EditScheduledMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  scheduledMessageId: types.string(),
  channelId: types.string(),
  text: types.string(),
  sendAt: types.number(),
  blocks: types.optional(z.array(models.MessageBlock$inboundSchema)),
  recurrence: types.optional(models.Recurrence$inboundSchema),
});
/** @internal */
export type EditScheduledMessageRequest$Outbound = {
  scheduledMessageId: string;
  channelId: string;
  text: string;
  sendAt: number;
  blocks?: Array<models.MessageBlock$Outbound> | undefined;
  recurrence?: models.Recurrence$Outbound | undefined;
};

/** @internal */
export const EditScheduledMessageRequest$outboundSchema: z.ZodType<
  EditScheduledMessageRequest$Outbound,
  z.ZodTypeDef,
  EditScheduledMessageRequest
> = z.object({
  scheduledMessageId: z.string(),
  channelId: z.string(),
  text: z.string(),
  sendAt: z.number().int(),
  blocks: z.array(models.MessageBlock$outboundSchema).optional(),
  recurrence: models.Recurrence$outboundSchema.optional(),
});

export function editScheduledMessageRequestToJSON(
  editScheduledMessageRequest: EditScheduledMessageRequest,
): string {
  return JSON.stringify(
    EditScheduledMessageRequest$outboundSchema.parse(
      editScheduledMessageRequest,
    ),
  );
}
export function editScheduledMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<EditScheduledMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditScheduledMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditScheduledMessageRequest' from JSON`,
  );
}
