/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type EditMessageRequest = {
  messageId: string;
  channelId: string;
  text: string;
  blocks?: Array<models.MessageBlock> | undefined;
};

/** @internal */
export const EditMessageRequest$inboundSchema: z.ZodType<
  EditMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: types.string(),
  channelId: types.string(),
  text: types.string(),
  blocks: types.optional(z.array(models.MessageBlock$inboundSchema)),
});
/** @internal */
export type EditMessageRequest$Outbound = {
  messageId: string;
  channelId: string;
  text: string;
  blocks?: Array<models.MessageBlock$Outbound> | undefined;
};

/** @internal */
export const EditMessageRequest$outboundSchema: z.ZodType<
  EditMessageRequest$Outbound,
  z.ZodTypeDef,
  EditMessageRequest
> = z.object({
  messageId: z.string(),
  channelId: z.string(),
  text: z.string(),
  blocks: z.array(models.MessageBlock$outboundSchema).optional(),
});

export function editMessageRequestToJSON(
  editMessageRequest: EditMessageRequest,
): string {
  return JSON.stringify(
    EditMessageRequest$outboundSchema.parse(editMessageRequest),
  );
}
export function editMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<EditMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditMessageRequest' from JSON`,
  );
}
