/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FetchScheduledMessageRequest = {
  scheduledMessageId: string;
};

/** @internal */
export const FetchScheduledMessageRequest$inboundSchema: z.ZodType<
  FetchScheduledMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  scheduledMessageId: types.string(),
});
/** @internal */
export type FetchScheduledMessageRequest$Outbound = {
  scheduledMessageId: string;
};

/** @internal */
export const FetchScheduledMessageRequest$outboundSchema: z.ZodType<
  FetchScheduledMessageRequest$Outbound,
  z.ZodTypeDef,
  FetchScheduledMessageRequest
> = z.object({
  scheduledMessageId: z.string(),
});

export function fetchScheduledMessageRequestToJSON(
  fetchScheduledMessageRequest: FetchScheduledMessageRequest,
): string {
  return JSON.stringify(
    FetchScheduledMessageRequest$outboundSchema.parse(
      fetchScheduledMessageRequest,
    ),
  );
}
export function fetchScheduledMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchScheduledMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchScheduledMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchScheduledMessageRequest' from JSON`,
  );
}
