/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetChannelRequest = {
  channelId?: string | undefined;
  channel?: string | undefined;
};

/**
 * Channel details.
 */
export type GetChannelResponse = {
  channel: models.Channel;
};

/** @internal */
export const GetChannelRequest$inboundSchema: z.ZodType<
  GetChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channelId: types.optional(types.string()),
  channel: types.optional(types.string()),
});
/** @internal */
export type GetChannelRequest$Outbound = {
  channelId?: string | undefined;
  channel?: string | undefined;
};

/** @internal */
export const GetChannelRequest$outboundSchema: z.ZodType<
  GetChannelRequest$Outbound,
  z.ZodTypeDef,
  GetChannelRequest
> = z.object({
  channelId: z.string().optional(),
  channel: z.string().optional(),
});

export function getChannelRequestToJSON(
  getChannelRequest: GetChannelRequest,
): string {
  return JSON.stringify(
    GetChannelRequest$outboundSchema.parse(getChannelRequest),
  );
}
export function getChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetChannelRequest' from JSON`,
  );
}

/** @internal */
export const GetChannelResponse$inboundSchema: z.ZodType<
  GetChannelResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel: models.Channel$inboundSchema,
});
/** @internal */
export type GetChannelResponse$Outbound = {
  channel: models.Channel$Outbound;
};

/** @internal */
export const GetChannelResponse$outboundSchema: z.ZodType<
  GetChannelResponse$Outbound,
  z.ZodTypeDef,
  GetChannelResponse
> = z.object({
  channel: models.Channel$outboundSchema,
});

export function getChannelResponseToJSON(
  getChannelResponse: GetChannelResponse,
): string {
  return JSON.stringify(
    GetChannelResponse$outboundSchema.parse(getChannelResponse),
  );
}
export function getChannelResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetChannelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetChannelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetChannelResponse' from JSON`,
  );
}
