/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListMessagesRequest = {
  channelId?: string | undefined;
  channel?: string | undefined;
  /**
   * ID of the last message on the previous page.
   */
  cursor?: string | undefined;
  limit?: number | undefined;
  /**
   * Pagination direction relative to `cursor`. When `cursor` is omitted the
   *
   * @remarks
   * server returns the most-recent page regardless of `strategy`.
   */
  strategy?: models.ListMessagesStrategy | undefined;
};

export type ListMessagesResponse = {
  result: models.MessageList;
};

/** @internal */
export const ListMessagesRequest$inboundSchema: z.ZodType<
  ListMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channelId: types.optional(types.string()),
  channel: types.optional(types.string()),
  cursor: types.optional(types.string()),
  limit: types.number().default(100),
  strategy: types.optional(models.ListMessagesStrategy$inboundSchema),
});
/** @internal */
export type ListMessagesRequest$Outbound = {
  channelId?: string | undefined;
  channel?: string | undefined;
  cursor?: string | undefined;
  limit: number;
  strategy?: string | undefined;
};

/** @internal */
export const ListMessagesRequest$outboundSchema: z.ZodType<
  ListMessagesRequest$Outbound,
  z.ZodTypeDef,
  ListMessagesRequest
> = z.object({
  channelId: z.string().optional(),
  channel: z.string().optional(),
  cursor: z.string().optional(),
  limit: z.number().int().default(100),
  strategy: models.ListMessagesStrategy$outboundSchema.optional(),
});

export function listMessagesRequestToJSON(
  listMessagesRequest: ListMessagesRequest,
): string {
  return JSON.stringify(
    ListMessagesRequest$outboundSchema.parse(listMessagesRequest),
  );
}
export function listMessagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListMessagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMessagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMessagesRequest' from JSON`,
  );
}

/** @internal */
export const ListMessagesResponse$inboundSchema: z.ZodType<
  ListMessagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.MessageList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListMessagesResponse$Outbound = {
  Result: models.MessageList$Outbound;
};

/** @internal */
export const ListMessagesResponse$outboundSchema: z.ZodType<
  ListMessagesResponse$Outbound,
  z.ZodTypeDef,
  ListMessagesResponse
> = z.object({
  result: models.MessageList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listMessagesResponseToJSON(
  listMessagesResponse: ListMessagesResponse,
): string {
  return JSON.stringify(
    ListMessagesResponse$outboundSchema.parse(listMessagesResponse),
  );
}
export function listMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMessagesResponse' from JSON`,
  );
}
