/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RemoveReactionRequest = {
  messageId: string;
  channelId?: string | undefined;
  /**
   * Emoji code in `:emoji_name:` form to remove.
   */
  reaction: string;
};

/**
 * Reaction removed.
 */
export type RemoveReactionResponse = {
  status?: string | undefined;
};

/** @internal */
export const RemoveReactionRequest$inboundSchema: z.ZodType<
  RemoveReactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: types.string(),
  channelId: types.optional(types.string()),
  reaction: types.string(),
});
/** @internal */
export type RemoveReactionRequest$Outbound = {
  messageId: string;
  channelId?: string | undefined;
  reaction: string;
};

/** @internal */
export const RemoveReactionRequest$outboundSchema: z.ZodType<
  RemoveReactionRequest$Outbound,
  z.ZodTypeDef,
  RemoveReactionRequest
> = z.object({
  messageId: z.string(),
  channelId: z.string().optional(),
  reaction: z.string(),
});

export function removeReactionRequestToJSON(
  removeReactionRequest: RemoveReactionRequest,
): string {
  return JSON.stringify(
    RemoveReactionRequest$outboundSchema.parse(removeReactionRequest),
  );
}
export function removeReactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemoveReactionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveReactionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveReactionRequest' from JSON`,
  );
}

/** @internal */
export const RemoveReactionResponse$inboundSchema: z.ZodType<
  RemoveReactionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: types.optional(types.string()),
});
/** @internal */
export type RemoveReactionResponse$Outbound = {
  status?: string | undefined;
};

/** @internal */
export const RemoveReactionResponse$outboundSchema: z.ZodType<
  RemoveReactionResponse$Outbound,
  z.ZodTypeDef,
  RemoveReactionResponse
> = z.object({
  status: z.string().optional(),
});

export function removeReactionResponseToJSON(
  removeReactionResponse: RemoveReactionResponse,
): string {
  return JSON.stringify(
    RemoveReactionResponse$outboundSchema.parse(removeReactionResponse),
  );
}
export function removeReactionResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveReactionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveReactionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveReactionResponse' from JSON`,
  );
}
