/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a2c1188a8c39
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RemoveUserFromChannelRequest = {
  channelId: string;
  userId: string;
};

/** @internal */
export const RemoveUserFromChannelRequest$inboundSchema: z.ZodType<
  RemoveUserFromChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channelId: types.string(),
  userId: types.string(),
});
/** @internal */
export type RemoveUserFromChannelRequest$Outbound = {
  channelId: string;
  userId: string;
};

/** @internal */
export const RemoveUserFromChannelRequest$outboundSchema: z.ZodType<
  RemoveUserFromChannelRequest$Outbound,
  z.ZodTypeDef,
  RemoveUserFromChannelRequest
> = z.object({
  channelId: z.string(),
  userId: z.string(),
});

export function removeUserFromChannelRequestToJSON(
  removeUserFromChannelRequest: RemoveUserFromChannelRequest,
): string {
  return JSON.stringify(
    RemoveUserFromChannelRequest$outboundSchema.parse(
      removeUserFromChannelRequest,
    ),
  );
}
export function removeUserFromChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemoveUserFromChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveUserFromChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveUserFromChannelRequest' from JSON`,
  );
}
