/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 85baae3c12bb
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SearchMessagesRequest = {
  text?: string | undefined;
  /**
   * Filter by sender user IDs.
   */
  from?: Array<string> | undefined;
  /**
   * Filter by channel IDs or names.
   */
  in?: Array<string> | undefined;
  limit?: number | undefined;
  strategy?: models.SearchStrategy | undefined;
  /**
   * Restrict to messages with `timestampMilli` strictly less than this value (also the pagination cursor).
   */
  beforeTs?: number | undefined;
  /**
   * Restrict to messages with `timestampMilli` strictly greater than this value.
   */
  afterTs?: number | undefined;
};

export type SearchMessagesResponse = {
  result: models.SearchMessagesResult;
};

/** @internal */
export const SearchMessagesRequest$inboundSchema: z.ZodType<
  SearchMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: types.optional(types.string()),
  from: types.optional(z.array(types.string())),
  in: types.optional(z.array(types.string())),
  limit: types.number().default(10),
  strategy: types.optional(models.SearchStrategy$inboundSchema),
  beforeTs: types.optional(types.number()),
  afterTs: types.optional(types.number()),
});
/** @internal */
export type SearchMessagesRequest$Outbound = {
  text?: string | undefined;
  from?: Array<string> | undefined;
  in?: Array<string> | undefined;
  limit: number;
  strategy?: string | undefined;
  beforeTs?: number | undefined;
  afterTs?: number | undefined;
};

/** @internal */
export const SearchMessagesRequest$outboundSchema: z.ZodType<
  SearchMessagesRequest$Outbound,
  z.ZodTypeDef,
  SearchMessagesRequest
> = z.object({
  text: z.string().optional(),
  from: z.array(z.string()).optional(),
  in: z.array(z.string()).optional(),
  limit: z.number().int().default(10),
  strategy: models.SearchStrategy$outboundSchema.optional(),
  beforeTs: z.number().int().optional(),
  afterTs: z.number().int().optional(),
});

export function searchMessagesRequestToJSON(
  searchMessagesRequest: SearchMessagesRequest,
): string {
  return JSON.stringify(
    SearchMessagesRequest$outboundSchema.parse(searchMessagesRequest),
  );
}
export function searchMessagesRequestFromJSON(
  jsonString: string,
): SafeParseResult<SearchMessagesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchMessagesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchMessagesRequest' from JSON`,
  );
}

/** @internal */
export const SearchMessagesResponse$inboundSchema: z.ZodType<
  SearchMessagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.SearchMessagesResult$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type SearchMessagesResponse$Outbound = {
  Result: models.SearchMessagesResult$Outbound;
};

/** @internal */
export const SearchMessagesResponse$outboundSchema: z.ZodType<
  SearchMessagesResponse$Outbound,
  z.ZodTypeDef,
  SearchMessagesResponse
> = z.object({
  result: models.SearchMessagesResult$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function searchMessagesResponseToJSON(
  searchMessagesResponse: SearchMessagesResponse,
): string {
  return JSON.stringify(
    SearchMessagesResponse$outboundSchema.parse(searchMessagesResponse),
  );
}
export function searchMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchMessagesResponse' from JSON`,
  );
}
