/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesAddReaction } from "../funcs/messages-add-reaction.js";
import { messagesDeleteMessage } from "../funcs/messages-delete-message.js";
import { messagesDmGroup } from "../funcs/messages-dm-group.js";
import { messagesDmUser } from "../funcs/messages-dm-user.js";
import { messagesEditMessage } from "../funcs/messages-edit-message.js";
import { messagesFetchMessage } from "../funcs/messages-fetch-message.js";
import { messagesFetchThreadReplies } from "../funcs/messages-fetch-thread-replies.js";
import { messagesListMessages } from "../funcs/messages-list-messages.js";
import { messagesRemoveReaction } from "../funcs/messages-remove-reaction.js";
import { messagesSearchMessages } from "../funcs/messages-search-messages.js";
import { messagesSendMessage } from "../funcs/messages-send-message.js";
import { messagesSendReply } from "../funcs/messages-send-reply.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Messages extends ClientSDK {
  /**
   * Send a message to a channel
   *
   * @remarks
   * Sends a text (or rich-text) message. Provide **either** `channelId`
   * (preferred) **or** `channel` (by name). If `threadRootId` is set, the
   * message is posted as a reply in that thread (equivalent to
   * `sendReply`).
   */
  async sendMessage(
    request: operations.SendMessageRequest,
    options?: RequestOptions,
  ): Promise<models.MessageRef> {
    return unwrapAsync(messagesSendMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Reply to a message in a channel (thread)
   *
   * @remarks
   * Posts `text` as a reply in the thread rooted at `messageId`. Provide
   * **either** `channelId` (preferred) **or** `channel` (by name).
   */
  async sendReply(
    request: operations.SendReplyRequest,
    options?: RequestOptions,
  ): Promise<models.MessageRef> {
    return unwrapAsync(messagesSendReply(
      this,
      request,
      options,
    ));
  }

  /**
   * Send a direct message to a user
   *
   * @remarks
   * Opens (or reuses) a 1-to-1 DM channel and posts a message. The
   * response's `channelId` is the DM channel — useful for follow-up
   * operations.
   */
  async dmUser(
    request: operations.DmUserRequest,
    options?: RequestOptions,
  ): Promise<models.MessageRef> {
    return unwrapAsync(messagesDmUser(
      this,
      request,
      options,
    ));
  }

  /**
   * Send a direct message to a group of users
   *
   * @remarks
   * Opens (or reuses) a multi-party DM channel and posts a message.
   */
  async dmGroup(
    request: operations.DmGroupRequest,
    options?: RequestOptions,
  ): Promise<models.MessageRef> {
    return unwrapAsync(messagesDmGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch a single message by ID
   */
  async fetchMessage(
    request: operations.FetchMessageRequest,
    options?: RequestOptions,
  ): Promise<models.Message> {
    return unwrapAsync(messagesFetchMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch the replies of a thread
   *
   * @remarks
   * Returns the replies posted in the thread rooted at `rootMessageId`,
   * as a flat array. Supports cursor pagination via the last reply's `id`.
   */
  async fetchThreadReplies(
    request: operations.FetchThreadRepliesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.FetchThreadRepliesResponse, { cursor: string }>
  > {
    return unwrapResultIterator(messagesFetchThreadReplies(
      this,
      request,
      options,
    ));
  }

  /**
   * Search messages
   *
   * @remarks
   * Searches messages by free text, sender, channel, and/or time window.
   * At least one of `text`, `from`, or `in` is required.
   *
   * ## Pagination
   * Cursor input is `beforeTs` (epoch ms); the next cursor is the
   * `timestampMilli` of the oldest hit in the current page. **Edge case**:
   * Pumble returns timestamps truncated to seconds, so messages sharing
   * the same `timestampMilli` that straddle a page boundary can be
   * skipped. For low-volume channels or `limit >= 10`, this is rarely
   * observed; for high-volume bursts use a smaller search window via
   * `afterTs` to bound the result set.
   */
  async searchMessages(
    request: operations.SearchMessagesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.SearchMessagesResponse, { cursor: number }>
  > {
    return unwrapResultIterator(messagesSearchMessages(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a message by ID
   */
  async deleteMessage(
    request: operations.DeleteMessageRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(messagesDeleteMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * List messages in a channel
   *
   * @remarks
   * Retrieves a paginated list of messages from a channel. Pagination is
   * cursor-based: pass the `id` of the last returned message as the next
   * `cursor`. `hasMoreBefore` / `hasMoreAfter` indicate which direction
   * still has messages relative to the cursor.
   */
  async listMessages(
    request?: operations.ListMessagesRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListMessagesResponse, { cursor: string }>
  > {
    return unwrapResultIterator(messagesListMessages(
      this,
      request,
      options,
    ));
  }

  /**
   * Add a reaction (emoji) to a message
   *
   * @remarks
   * Adds a reaction code in `:emoji_name:` form. Pumble enforces the
   * colon-wrapped form server-side; bare names (e.g. `+1`) return 403.
   */
  async addReaction(
    request: operations.AddReactionRequest,
    options?: RequestOptions,
  ): Promise<operations.AddReactionResponse> {
    return unwrapAsync(messagesAddReaction(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a reaction from a message
   */
  async removeReaction(
    request: operations.RemoveReactionRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveReactionResponse> {
    return unwrapAsync(messagesRemoveReaction(
      this,
      request,
      options,
    ));
  }

  /**
   * Edit a message
   */
  async editMessage(
    request: operations.EditMessageRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(messagesEditMessage(
      this,
      request,
      options,
    ));
  }
}
