/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledMessagesCreateScheduledMessage } from "../funcs/scheduled-messages-create-scheduled-message.js";
import { scheduledMessagesDeleteScheduledMessage } from "../funcs/scheduled-messages-delete-scheduled-message.js";
import { scheduledMessagesEditScheduledMessage } from "../funcs/scheduled-messages-edit-scheduled-message.js";
import { scheduledMessagesFetchScheduledMessage } from "../funcs/scheduled-messages-fetch-scheduled-message.js";
import { scheduledMessagesFetchScheduledMessages } from "../funcs/scheduled-messages-fetch-scheduled-messages.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class ScheduledMessages extends ClientSDK {
  /**
   * Create a scheduled (future) message
   */
  async createScheduledMessage(
    request: operations.CreateScheduledMessageRequest,
    options?: RequestOptions,
  ): Promise<models.ScheduledMessageRef> {
    return unwrapAsync(scheduledMessagesCreateScheduledMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch a list of scheduled messages
   *
   * @remarks
   * Returns scheduled messages for the workspace (optionally filtered to
   * a single channel). Cursor pagination uses the last scheduled
   * message's `id`.
   */
  async fetchScheduledMessages(
    request?: operations.FetchScheduledMessagesRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.FetchScheduledMessagesResponse, { cursor: string }>
  > {
    return unwrapResultIterator(scheduledMessagesFetchScheduledMessages(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch a single scheduled message by ID
   */
  async fetchScheduledMessage(
    request: operations.FetchScheduledMessageRequest,
    options?: RequestOptions,
  ): Promise<models.ScheduledMessage> {
    return unwrapAsync(scheduledMessagesFetchScheduledMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Edit a scheduled message
   *
   * @remarks
   * Updates a queued scheduled message. **All of** `scheduledMessageId`,
   * `channelId`, `text`, and `sendAt` are required server-side — omitting
   * any of them returns 403 with `[must not be null]`. Pass the existing
   * `sendAt` value verbatim if you don't want to reschedule.
   */
  async editScheduledMessage(
    request: operations.EditScheduledMessageRequest,
    options?: RequestOptions,
  ): Promise<models.ScheduledMessage> {
    return unwrapAsync(scheduledMessagesEditScheduledMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a scheduled message
   */
  async deleteScheduledMessage(
    request: operations.DeleteScheduledMessageRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(scheduledMessagesDeleteScheduledMessage(
      this,
      request,
      options,
    ));
  }
}
