/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ChannelType,
  ChannelType$inboundSchema,
  ChannelType$outboundSchema,
} from "./channel-type.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PostingPermissions,
  PostingPermissions$inboundSchema,
  PostingPermissions$Outbound,
  PostingPermissions$outboundSchema,
} from "./posting-permissions.js";

export type Channel = {
  id: string;
  name: string;
  /**
   * Optional channel description (empty string if unset).
   */
  description?: string | undefined;
  /**
   * Visibility of a channel.
   */
  channelType: ChannelType;
  creatorId?: string | undefined;
  /**
   * User ID that added the current user to the channel (`null` for channels the current user created or that pre-date this tracking).
   */
  addedById?: string | null | undefined;
  workspaceId: string;
  /**
   * Section the channel belongs to (empty if none).
   */
  sectionId?: string | undefined;
  isArchived?: boolean | undefined;
  isHidden?: boolean | undefined;
  isMember?: boolean | undefined;
  isMuted?: boolean | undefined;
  isMain?: boolean | undefined;
  isInitial?: boolean | undefined;
  isAddonBot?: boolean | undefined;
  isPumbleBot?: boolean | undefined;
  notifyAboutRepliesInThreads?: boolean | undefined;
  lastMessageTimestamp?: Date | undefined;
  lastMessageTimestampMilli?: number | undefined;
  lastMarkTimestamp?: Date | undefined;
  lastMarkTimestampMilli?: number | undefined;
  timestamp?: Date | undefined;
  timestampMilli?: number | undefined;
  postingPermissions?: PostingPermissions | undefined;
  /**
   * Notification preference for this channel on desktop (e.g. `EVERYTHING`, `MENTIONS`, `NONE`); `null` if no per-channel override.
   */
  desktopNotificationPreferences?: string | null | undefined;
  /**
   * Notification preference for this channel on mobile; `null` if no per-channel override.
   */
  mobileNotificationPreferences?: string | null | undefined;
};

/** @internal */
export const Channel$inboundSchema: z.ZodType<Channel, z.ZodTypeDef, unknown> =
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.optional(types.string()),
    channelType: ChannelType$inboundSchema,
    creatorId: types.optional(types.string()),
    addedById: z.nullable(types.string()).optional(),
    workspaceId: types.string(),
    sectionId: types.optional(types.string()),
    isArchived: types.optional(types.boolean()),
    isHidden: types.optional(types.boolean()),
    isMember: types.optional(types.boolean()),
    isMuted: types.optional(types.boolean()),
    isMain: types.optional(types.boolean()),
    isInitial: types.optional(types.boolean()),
    isAddonBot: types.optional(types.boolean()),
    isPumbleBot: types.optional(types.boolean()),
    notifyAboutRepliesInThreads: types.optional(types.boolean()),
    lastMessageTimestamp: types.optional(types.date()),
    lastMessageTimestampMilli: types.optional(types.number()),
    lastMarkTimestamp: types.optional(types.date()),
    lastMarkTimestampMilli: types.optional(types.number()),
    timestamp: types.optional(types.date()),
    timestampMilli: types.optional(types.number()),
    postingPermissions: types.optional(PostingPermissions$inboundSchema),
    desktopNotificationPreferences: z.nullable(types.string()).optional(),
    mobileNotificationPreferences: z.nullable(types.string()).optional(),
  });
/** @internal */
export type Channel$Outbound = {
  id: string;
  name: string;
  description?: string | undefined;
  channelType: string;
  creatorId?: string | undefined;
  addedById?: string | null | undefined;
  workspaceId: string;
  sectionId?: string | undefined;
  isArchived?: boolean | undefined;
  isHidden?: boolean | undefined;
  isMember?: boolean | undefined;
  isMuted?: boolean | undefined;
  isMain?: boolean | undefined;
  isInitial?: boolean | undefined;
  isAddonBot?: boolean | undefined;
  isPumbleBot?: boolean | undefined;
  notifyAboutRepliesInThreads?: boolean | undefined;
  lastMessageTimestamp?: string | undefined;
  lastMessageTimestampMilli?: number | undefined;
  lastMarkTimestamp?: string | undefined;
  lastMarkTimestampMilli?: number | undefined;
  timestamp?: string | undefined;
  timestampMilli?: number | undefined;
  postingPermissions?: PostingPermissions$Outbound | undefined;
  desktopNotificationPreferences?: string | null | undefined;
  mobileNotificationPreferences?: string | null | undefined;
};

/** @internal */
export const Channel$outboundSchema: z.ZodType<
  Channel$Outbound,
  z.ZodTypeDef,
  Channel
> = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional(),
  channelType: ChannelType$outboundSchema,
  creatorId: z.string().optional(),
  addedById: z.nullable(z.string()).optional(),
  workspaceId: z.string(),
  sectionId: z.string().optional(),
  isArchived: z.boolean().optional(),
  isHidden: z.boolean().optional(),
  isMember: z.boolean().optional(),
  isMuted: z.boolean().optional(),
  isMain: z.boolean().optional(),
  isInitial: z.boolean().optional(),
  isAddonBot: z.boolean().optional(),
  isPumbleBot: z.boolean().optional(),
  notifyAboutRepliesInThreads: z.boolean().optional(),
  lastMessageTimestamp: z.date().transform(v => v.toISOString()).optional(),
  lastMessageTimestampMilli: z.number().int().optional(),
  lastMarkTimestamp: z.date().transform(v => v.toISOString()).optional(),
  lastMarkTimestampMilli: z.number().int().optional(),
  timestamp: z.date().transform(v => v.toISOString()).optional(),
  timestampMilli: z.number().int().optional(),
  postingPermissions: PostingPermissions$outboundSchema.optional(),
  desktopNotificationPreferences: z.nullable(z.string()).optional(),
  mobileNotificationPreferences: z.nullable(z.string()).optional(),
});

export function channelToJSON(channel: Channel): string {
  return JSON.stringify(Channel$outboundSchema.parse(channel));
}
export function channelFromJSON(
  jsonString: string,
): SafeParseResult<Channel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Channel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Channel' from JSON`,
  );
}
