/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3e325b85124e
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Visibility of a channel.
 */
export const ChannelType = {
  Public: "PUBLIC",
  Private: "PRIVATE",
} as const;
/**
 * Visibility of a channel.
 */
export type ChannelType = OpenEnum<typeof ChannelType>;

/** @internal */
export const ChannelType$inboundSchema: z.ZodType<
  ChannelType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ChannelType);
/** @internal */
export const ChannelType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ChannelType
> = openEnums.outboundSchema(ChannelType);
