/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6349597922e5
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Pagination direction relative to `cursor`. When `cursor` is omitted the
 *
 * @remarks
 * server returns the most-recent page regardless of `strategy`.
 */
export const ListMessagesStrategy = {
  Before: "BEFORE",
  After: "AFTER",
  Around: "AROUND",
} as const;
/**
 * Pagination direction relative to `cursor`. When `cursor` is omitted the
 *
 * @remarks
 * server returns the most-recent page regardless of `strategy`.
 */
export type ListMessagesStrategy = ClosedEnum<typeof ListMessagesStrategy>;

/** @internal */
export const ListMessagesStrategy$inboundSchema: z.ZodNativeEnum<
  typeof ListMessagesStrategy
> = z.nativeEnum(ListMessagesStrategy);
/** @internal */
export const ListMessagesStrategy$outboundSchema: z.ZodNativeEnum<
  typeof ListMessagesStrategy
> = ListMessagesStrategy$inboundSchema;
