/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eca57c4fcfe1
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MessageBlock,
  MessageBlock$inboundSchema,
  MessageBlock$Outbound,
  MessageBlock$outboundSchema,
} from "./message-block.js";
import {
  Reaction,
  Reaction$inboundSchema,
  Reaction$Outbound,
  Reaction$outboundSchema,
} from "./reaction.js";

export type MessageThreadRootInfo = {
  replyCount?: number | undefined;
  lastReplyTimestampMilli?: number | undefined;
};

export type MessageThreadReplyInfo = {
  rootId?: string | undefined;
  replySentToChannel?: boolean | undefined;
  rootText?: string | undefined;
};

export type Message = {
  id: string;
  channelId: string;
  workspaceId: string;
  /**
   * ID of the user (or addon) that sent the message.
   */
  author: string;
  /**
   * ID of the addon app that authored the message (null for human-authored).
   */
  authorAppId?: string | null | undefined;
  text: string;
  blocks?: Array<MessageBlock> | null | undefined;
  attachments?: Array<{ [k: string]: any }> | undefined;
  files?: Array<{ [k: string]: any }> | undefined;
  reactions?: Array<Reaction> | undefined;
  linkPreviews?: Array<{ [k: string]: any }> | undefined;
  threadRootInfo?: MessageThreadRootInfo | null | undefined;
  threadReplyInfo?: MessageThreadReplyInfo | null | undefined;
  deleted?: boolean | undefined;
  edited?: boolean | undefined;
  isFollowing?: boolean | undefined;
  /**
   * Message subtype (empty string for normal messages).
   */
  subtype?: string | undefined;
  localId?: string | undefined;
  meta?: { [k: string]: any } | null | undefined;
  savedTimestampMilli?: number | undefined;
  timestamp: Date;
  timestampMilli: number;
};

/** @internal */
export const MessageThreadRootInfo$inboundSchema: z.ZodType<
  MessageThreadRootInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  replyCount: types.optional(types.number()),
  lastReplyTimestampMilli: types.optional(types.number()),
});
/** @internal */
export type MessageThreadRootInfo$Outbound = {
  replyCount?: number | undefined;
  lastReplyTimestampMilli?: number | undefined;
};

/** @internal */
export const MessageThreadRootInfo$outboundSchema: z.ZodType<
  MessageThreadRootInfo$Outbound,
  z.ZodTypeDef,
  MessageThreadRootInfo
> = z.object({
  replyCount: z.number().int().optional(),
  lastReplyTimestampMilli: z.number().int().optional(),
});

export function messageThreadRootInfoToJSON(
  messageThreadRootInfo: MessageThreadRootInfo,
): string {
  return JSON.stringify(
    MessageThreadRootInfo$outboundSchema.parse(messageThreadRootInfo),
  );
}
export function messageThreadRootInfoFromJSON(
  jsonString: string,
): SafeParseResult<MessageThreadRootInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageThreadRootInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageThreadRootInfo' from JSON`,
  );
}

/** @internal */
export const MessageThreadReplyInfo$inboundSchema: z.ZodType<
  MessageThreadReplyInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  rootId: types.optional(types.string()),
  replySentToChannel: types.optional(types.boolean()),
  rootText: types.optional(types.string()),
});
/** @internal */
export type MessageThreadReplyInfo$Outbound = {
  rootId?: string | undefined;
  replySentToChannel?: boolean | undefined;
  rootText?: string | undefined;
};

/** @internal */
export const MessageThreadReplyInfo$outboundSchema: z.ZodType<
  MessageThreadReplyInfo$Outbound,
  z.ZodTypeDef,
  MessageThreadReplyInfo
> = z.object({
  rootId: z.string().optional(),
  replySentToChannel: z.boolean().optional(),
  rootText: z.string().optional(),
});

export function messageThreadReplyInfoToJSON(
  messageThreadReplyInfo: MessageThreadReplyInfo,
): string {
  return JSON.stringify(
    MessageThreadReplyInfo$outboundSchema.parse(messageThreadReplyInfo),
  );
}
export function messageThreadReplyInfoFromJSON(
  jsonString: string,
): SafeParseResult<MessageThreadReplyInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageThreadReplyInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageThreadReplyInfo' from JSON`,
  );
}

/** @internal */
export const Message$inboundSchema: z.ZodType<Message, z.ZodTypeDef, unknown> =
  z.object({
    id: types.string(),
    channelId: types.string(),
    workspaceId: types.string(),
    author: types.string(),
    authorAppId: z.nullable(types.string()).optional(),
    text: types.string(),
    blocks: z.nullable(z.array(MessageBlock$inboundSchema)).optional(),
    attachments: types.optional(z.array(z.record(z.any()))),
    files: types.optional(z.array(z.record(z.any()))),
    reactions: types.optional(z.array(Reaction$inboundSchema)),
    linkPreviews: types.optional(z.array(z.record(z.any()))),
    threadRootInfo: z.nullable(
      z.lazy(() => MessageThreadRootInfo$inboundSchema),
    ).optional(),
    threadReplyInfo: z.nullable(
      z.lazy(() => MessageThreadReplyInfo$inboundSchema),
    ).optional(),
    deleted: types.optional(types.boolean()),
    edited: types.optional(types.boolean()),
    isFollowing: types.optional(types.boolean()),
    subtype: types.optional(types.string()),
    localId: types.optional(types.string()),
    meta: z.nullable(z.record(z.any())).optional(),
    savedTimestampMilli: types.optional(types.number()),
    timestamp: types.date(),
    timestampMilli: types.number(),
  });
/** @internal */
export type Message$Outbound = {
  id: string;
  channelId: string;
  workspaceId: string;
  author: string;
  authorAppId?: string | null | undefined;
  text: string;
  blocks?: Array<MessageBlock$Outbound> | null | undefined;
  attachments?: Array<{ [k: string]: any }> | undefined;
  files?: Array<{ [k: string]: any }> | undefined;
  reactions?: Array<Reaction$Outbound> | undefined;
  linkPreviews?: Array<{ [k: string]: any }> | undefined;
  threadRootInfo?: MessageThreadRootInfo$Outbound | null | undefined;
  threadReplyInfo?: MessageThreadReplyInfo$Outbound | null | undefined;
  deleted?: boolean | undefined;
  edited?: boolean | undefined;
  isFollowing?: boolean | undefined;
  subtype?: string | undefined;
  localId?: string | undefined;
  meta?: { [k: string]: any } | null | undefined;
  savedTimestampMilli?: number | undefined;
  timestamp: string;
  timestampMilli: number;
};

/** @internal */
export const Message$outboundSchema: z.ZodType<
  Message$Outbound,
  z.ZodTypeDef,
  Message
> = z.object({
  id: z.string(),
  channelId: z.string(),
  workspaceId: z.string(),
  author: z.string(),
  authorAppId: z.nullable(z.string()).optional(),
  text: z.string(),
  blocks: z.nullable(z.array(MessageBlock$outboundSchema)).optional(),
  attachments: z.array(z.record(z.any())).optional(),
  files: z.array(z.record(z.any())).optional(),
  reactions: z.array(Reaction$outboundSchema).optional(),
  linkPreviews: z.array(z.record(z.any())).optional(),
  threadRootInfo: z.nullable(z.lazy(() => MessageThreadRootInfo$outboundSchema))
    .optional(),
  threadReplyInfo: z.nullable(
    z.lazy(() => MessageThreadReplyInfo$outboundSchema),
  ).optional(),
  deleted: z.boolean().optional(),
  edited: z.boolean().optional(),
  isFollowing: z.boolean().optional(),
  subtype: z.string().optional(),
  localId: z.string().optional(),
  meta: z.nullable(z.record(z.any())).optional(),
  savedTimestampMilli: z.number().int().optional(),
  timestamp: z.date().transform(v => v.toISOString()),
  timestampMilli: z.number().int(),
});

export function messageToJSON(message: Message): string {
  return JSON.stringify(Message$outboundSchema.parse(message));
}
export function messageFromJSON(
  jsonString: string,
): SafeParseResult<Message, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Message$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Message' from JSON`,
  );
}
