/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9ca3acaf2304
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  RichTextElement,
  RichTextElement$inboundSchema,
  RichTextElement$Outbound,
  RichTextElement$outboundSchema,
} from "./rich-text-element.js";

export type MessageBlock = {
  type?: string | undefined;
  elements?: Array<RichTextElement> | undefined;
};

/** @internal */
export const MessageBlock$inboundSchema: z.ZodType<
  MessageBlock,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: types.optional(types.string()),
  elements: types.optional(z.array(RichTextElement$inboundSchema)),
});
/** @internal */
export type MessageBlock$Outbound = {
  type?: string | undefined;
  elements?: Array<RichTextElement$Outbound> | undefined;
};

/** @internal */
export const MessageBlock$outboundSchema: z.ZodType<
  MessageBlock$Outbound,
  z.ZodTypeDef,
  MessageBlock
> = z.object({
  type: z.string().optional(),
  elements: z.array(RichTextElement$outboundSchema).optional(),
});

export function messageBlockToJSON(messageBlock: MessageBlock): string {
  return JSON.stringify(MessageBlock$outboundSchema.parse(messageBlock));
}
export function messageBlockFromJSON(
  jsonString: string,
): SafeParseResult<MessageBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageBlock' from JSON`,
  );
}
