/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  Message,
  Message$inboundSchema,
  Message$Outbound,
  Message$outboundSchema,
} from "./message.js";

/**
 * Paginated message list. `hasMoreBefore` / `hasMoreAfter` are nullable —
 *
 * @remarks
 * the server returns `null` for the side that's irrelevant to the chosen
 * `strategy` (e.g. `strategy=AFTER` yields `hasMoreBefore=null`).
 */
export type MessageList = {
  messages: Array<Message>;
  hasMoreBefore?: boolean | null | undefined;
  hasMoreAfter?: boolean | null | undefined;
};

/** @internal */
export const MessageList$inboundSchema: z.ZodType<
  MessageList,
  z.ZodTypeDef,
  unknown
> = z.object({
  messages: z.array(Message$inboundSchema),
  hasMoreBefore: z.nullable(types.boolean()).optional(),
  hasMoreAfter: z.nullable(types.boolean()).optional(),
});
/** @internal */
export type MessageList$Outbound = {
  messages: Array<Message$Outbound>;
  hasMoreBefore?: boolean | null | undefined;
  hasMoreAfter?: boolean | null | undefined;
};

/** @internal */
export const MessageList$outboundSchema: z.ZodType<
  MessageList$Outbound,
  z.ZodTypeDef,
  MessageList
> = z.object({
  messages: z.array(Message$outboundSchema),
  hasMoreBefore: z.nullable(z.boolean()).optional(),
  hasMoreAfter: z.nullable(z.boolean()).optional(),
});

export function messageListToJSON(messageList: MessageList): string {
  return JSON.stringify(MessageList$outboundSchema.parse(messageList));
}
export function messageListFromJSON(
  jsonString: string,
): SafeParseResult<MessageList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageList' from JSON`,
  );
}
