/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PostingPermissionsGroup,
  PostingPermissionsGroup$inboundSchema,
  PostingPermissionsGroup$outboundSchema,
} from "./posting-permissions-group.js";

export type PostingPermissions = {
  allowThreads?: boolean | undefined;
  allowMentions?: boolean | undefined;
  postingPermissionsGroup?: PostingPermissionsGroup | undefined;
  workspaceUserIds?: Array<string> | undefined;
};

/** @internal */
export const PostingPermissions$inboundSchema: z.ZodType<
  PostingPermissions,
  z.ZodTypeDef,
  unknown
> = z.object({
  allowThreads: types.optional(types.boolean()),
  allowMentions: types.optional(types.boolean()),
  postingPermissionsGroup: types.optional(
    PostingPermissionsGroup$inboundSchema,
  ),
  workspaceUserIds: types.optional(z.array(types.string())),
});
/** @internal */
export type PostingPermissions$Outbound = {
  allowThreads?: boolean | undefined;
  allowMentions?: boolean | undefined;
  postingPermissionsGroup?: string | undefined;
  workspaceUserIds?: Array<string> | undefined;
};

/** @internal */
export const PostingPermissions$outboundSchema: z.ZodType<
  PostingPermissions$Outbound,
  z.ZodTypeDef,
  PostingPermissions
> = z.object({
  allowThreads: z.boolean().optional(),
  allowMentions: z.boolean().optional(),
  postingPermissionsGroup: PostingPermissionsGroup$outboundSchema.optional(),
  workspaceUserIds: z.array(z.string()).optional(),
});

export function postingPermissionsToJSON(
  postingPermissions: PostingPermissions,
): string {
  return JSON.stringify(
    PostingPermissions$outboundSchema.parse(postingPermissions),
  );
}
export function postingPermissionsFromJSON(
  jsonString: string,
): SafeParseResult<PostingPermissions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostingPermissions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostingPermissions' from JSON`,
  );
}
