/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Reaction = {
  /**
   * User ID that added the reaction.
   */
  user: string;
  /**
   * Emoji code in `:emoji_name:` form.
   */
  code: string;
};

/** @internal */
export const Reaction$inboundSchema: z.ZodType<
  Reaction,
  z.ZodTypeDef,
  unknown
> = z.object({
  user: types.string(),
  code: types.string(),
});
/** @internal */
export type Reaction$Outbound = {
  user: string;
  code: string;
};

/** @internal */
export const Reaction$outboundSchema: z.ZodType<
  Reaction$Outbound,
  z.ZodTypeDef,
  Reaction
> = z.object({
  user: z.string(),
  code: z.string(),
});

export function reactionToJSON(reaction: Reaction): string {
  return JSON.stringify(Reaction$outboundSchema.parse(reaction));
}
export function reactionFromJSON(
  jsonString: string,
): SafeParseResult<Reaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Reaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Reaction' from JSON`,
  );
}
