/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0279749a1c4c
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  RecurrenceType,
  RecurrenceType$inboundSchema,
  RecurrenceType$outboundSchema,
} from "./recurrence-type.js";

export type Recurrence = {
  recurrenceType: RecurrenceType;
  endAfterOccurrences?: number | undefined;
  /**
   * Epoch-ms after which the recurrence stops.
   */
  endDate?: number | undefined;
};

/** @internal */
export const Recurrence$inboundSchema: z.ZodType<
  Recurrence,
  z.ZodTypeDef,
  unknown
> = z.object({
  recurrenceType: RecurrenceType$inboundSchema,
  endAfterOccurrences: types.optional(types.number()),
  endDate: types.optional(types.number()),
});
/** @internal */
export type Recurrence$Outbound = {
  recurrenceType: string;
  endAfterOccurrences?: number | undefined;
  endDate?: number | undefined;
};

/** @internal */
export const Recurrence$outboundSchema: z.ZodType<
  Recurrence$Outbound,
  z.ZodTypeDef,
  Recurrence
> = z.object({
  recurrenceType: RecurrenceType$outboundSchema,
  endAfterOccurrences: z.number().int().optional(),
  endDate: z.number().int().optional(),
});

export function recurrenceToJSON(recurrence: Recurrence): string {
  return JSON.stringify(Recurrence$outboundSchema.parse(recurrence));
}
export function recurrenceFromJSON(
  jsonString: string,
): SafeParseResult<Recurrence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Recurrence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Recurrence' from JSON`,
  );
}
