/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b8046f1f5491
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * One node in Pumble's rich-text block structure. The full grammar is
 *
 * @remarks
 * large (Slack-like); only top-level fields are typed here.
 */
export type RichTextElement = {
  type?: string | undefined;
  text?: string | undefined;
  elements?: Array<RichTextElement> | undefined;
  /**
   * Present on search-hit blocks to indicate matching text.
   */
  highlight?: string | undefined;
};

/** @internal */
export const RichTextElement$inboundSchema: z.ZodType<
  RichTextElement,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: types.optional(types.string()),
  text: types.optional(types.string()),
  elements: types.optional(
    z.array(z.lazy(() => RichTextElement$inboundSchema)),
  ),
  highlight: types.optional(types.string()),
});
/** @internal */
export type RichTextElement$Outbound = {
  type?: string | undefined;
  text?: string | undefined;
  elements?: Array<RichTextElement$Outbound> | undefined;
  highlight?: string | undefined;
};

/** @internal */
export const RichTextElement$outboundSchema: z.ZodType<
  RichTextElement$Outbound,
  z.ZodTypeDef,
  RichTextElement
> = z.object({
  type: z.string().optional(),
  text: z.string().optional(),
  elements: z.array(z.lazy(() => RichTextElement$outboundSchema)).optional(),
  highlight: z.string().optional(),
});

export function richTextElementToJSON(
  richTextElement: RichTextElement,
): string {
  return JSON.stringify(RichTextElement$outboundSchema.parse(richTextElement));
}
export function richTextElementFromJSON(
  jsonString: string,
): SafeParseResult<RichTextElement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RichTextElement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RichTextElement' from JSON`,
  );
}
