/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 699cf1fb9c42
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ScheduledMessage,
  ScheduledMessage$inboundSchema,
  ScheduledMessage$Outbound,
  ScheduledMessage$outboundSchema,
} from "./scheduled-message.js";

export type ScheduledMessageList = {
  scheduledMessages: Array<ScheduledMessage>;
  hasMore: boolean;
};

/** @internal */
export const ScheduledMessageList$inboundSchema: z.ZodType<
  ScheduledMessageList,
  z.ZodTypeDef,
  unknown
> = z.object({
  scheduledMessages: z.array(ScheduledMessage$inboundSchema),
  hasMore: types.boolean(),
});
/** @internal */
export type ScheduledMessageList$Outbound = {
  scheduledMessages: Array<ScheduledMessage$Outbound>;
  hasMore: boolean;
};

/** @internal */
export const ScheduledMessageList$outboundSchema: z.ZodType<
  ScheduledMessageList$Outbound,
  z.ZodTypeDef,
  ScheduledMessageList
> = z.object({
  scheduledMessages: z.array(ScheduledMessage$outboundSchema),
  hasMore: z.boolean(),
});

export function scheduledMessageListToJSON(
  scheduledMessageList: ScheduledMessageList,
): string {
  return JSON.stringify(
    ScheduledMessageList$outboundSchema.parse(scheduledMessageList),
  );
}
export function scheduledMessageListFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledMessageList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledMessageList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledMessageList' from JSON`,
  );
}
