/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b52b4db8e484
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MessageBlock,
  MessageBlock$inboundSchema,
  MessageBlock$Outbound,
  MessageBlock$outboundSchema,
} from "./message-block.js";
import {
  RecurrenceType,
  RecurrenceType$inboundSchema,
  RecurrenceType$outboundSchema,
} from "./recurrence-type.js";

export type ScheduledMessageRecurrence = {
  recurrenceType: RecurrenceType;
  endAfterOccurrences?: number | undefined;
  /**
   * Epoch-ms after which the recurrence stops.
   */
  endDate?: number | undefined;
};

export type ScheduledMessage = {
  id: string;
  channelId: string;
  workspaceId: string;
  author: string;
  text: string;
  /**
   * Delivery moment (epoch ms).
   */
  sendAt: number;
  blocks?: Array<MessageBlock> | undefined;
  attachments?: Array<{ [k: string]: any }> | undefined;
  files?: Array<{ [k: string]: any }> | undefined;
  /**
   * For threaded scheduled messages, whether to also broadcast to the parent channel on send.
   */
  alsoSendToChannel?: boolean | undefined;
  threadRootId?: string | null | undefined;
  rootText?: string | null | undefined;
  quotedMessage?: { [k: string]: any } | null | undefined;
  recurrence?: ScheduledMessageRecurrence | null | undefined;
};

/** @internal */
export const ScheduledMessageRecurrence$inboundSchema: z.ZodType<
  ScheduledMessageRecurrence,
  z.ZodTypeDef,
  unknown
> = z.object({
  recurrenceType: RecurrenceType$inboundSchema,
  endAfterOccurrences: types.optional(types.number()),
  endDate: types.optional(types.number()),
});
/** @internal */
export type ScheduledMessageRecurrence$Outbound = {
  recurrenceType: string;
  endAfterOccurrences?: number | undefined;
  endDate?: number | undefined;
};

/** @internal */
export const ScheduledMessageRecurrence$outboundSchema: z.ZodType<
  ScheduledMessageRecurrence$Outbound,
  z.ZodTypeDef,
  ScheduledMessageRecurrence
> = z.object({
  recurrenceType: RecurrenceType$outboundSchema,
  endAfterOccurrences: z.number().int().optional(),
  endDate: z.number().int().optional(),
});

export function scheduledMessageRecurrenceToJSON(
  scheduledMessageRecurrence: ScheduledMessageRecurrence,
): string {
  return JSON.stringify(
    ScheduledMessageRecurrence$outboundSchema.parse(scheduledMessageRecurrence),
  );
}
export function scheduledMessageRecurrenceFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledMessageRecurrence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledMessageRecurrence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledMessageRecurrence' from JSON`,
  );
}

/** @internal */
export const ScheduledMessage$inboundSchema: z.ZodType<
  ScheduledMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.string(),
  channelId: types.string(),
  workspaceId: types.string(),
  author: types.string(),
  text: types.string(),
  sendAt: types.number(),
  blocks: types.optional(z.array(MessageBlock$inboundSchema)),
  attachments: types.optional(z.array(z.record(z.any()))),
  files: types.optional(z.array(z.record(z.any()))),
  alsoSendToChannel: types.optional(types.boolean()),
  threadRootId: z.nullable(types.string()).optional(),
  rootText: z.nullable(types.string()).optional(),
  quotedMessage: z.nullable(z.record(z.any())).optional(),
  recurrence: z.nullable(z.lazy(() => ScheduledMessageRecurrence$inboundSchema))
    .optional(),
});
/** @internal */
export type ScheduledMessage$Outbound = {
  id: string;
  channelId: string;
  workspaceId: string;
  author: string;
  text: string;
  sendAt: number;
  blocks?: Array<MessageBlock$Outbound> | undefined;
  attachments?: Array<{ [k: string]: any }> | undefined;
  files?: Array<{ [k: string]: any }> | undefined;
  alsoSendToChannel?: boolean | undefined;
  threadRootId?: string | null | undefined;
  rootText?: string | null | undefined;
  quotedMessage?: { [k: string]: any } | null | undefined;
  recurrence?: ScheduledMessageRecurrence$Outbound | null | undefined;
};

/** @internal */
export const ScheduledMessage$outboundSchema: z.ZodType<
  ScheduledMessage$Outbound,
  z.ZodTypeDef,
  ScheduledMessage
> = z.object({
  id: z.string(),
  channelId: z.string(),
  workspaceId: z.string(),
  author: z.string(),
  text: z.string(),
  sendAt: z.number().int(),
  blocks: z.array(MessageBlock$outboundSchema).optional(),
  attachments: z.array(z.record(z.any())).optional(),
  files: z.array(z.record(z.any())).optional(),
  alsoSendToChannel: z.boolean().optional(),
  threadRootId: z.nullable(z.string()).optional(),
  rootText: z.nullable(z.string()).optional(),
  quotedMessage: z.nullable(z.record(z.any())).optional(),
  recurrence: z.nullable(
    z.lazy(() => ScheduledMessageRecurrence$outboundSchema),
  ).optional(),
});

export function scheduledMessageToJSON(
  scheduledMessage: ScheduledMessage,
): string {
  return JSON.stringify(
    ScheduledMessage$outboundSchema.parse(scheduledMessage),
  );
}
export function scheduledMessageFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledMessage' from JSON`,
  );
}
