/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MessageBlock,
  MessageBlock$inboundSchema,
  MessageBlock$Outbound,
  MessageBlock$outboundSchema,
} from "./message-block.js";
import {
  Reaction,
  Reaction$inboundSchema,
  Reaction$Outbound,
  Reaction$outboundSchema,
} from "./reaction.js";

export type SearchHitThreadRootInfo = {
  replyCount?: number | undefined;
  lastReplyTimestampMilli?: number | undefined;
};

export type SearchHitThreadReplyInfo = {
  rootId?: string | undefined;
  replySentToChannel?: boolean | undefined;
  rootText?: string | undefined;
};

export type SearchHit = {
  id: string;
  channelId: string;
  workspaceId: string;
  /**
   * ID of the user (or addon) that sent the message.
   */
  author: string;
  /**
   * ID of the addon app that authored the message (null for human-authored).
   */
  authorAppId?: string | null | undefined;
  text: string;
  blocks?: Array<MessageBlock> | null | undefined;
  attachments?: Array<{ [k: string]: any }> | undefined;
  files?: Array<{ [k: string]: any }> | undefined;
  reactions?: Array<Reaction> | undefined;
  linkPreviews?: Array<{ [k: string]: any }> | undefined;
  threadRootInfo?: SearchHitThreadRootInfo | null | undefined;
  threadReplyInfo?: SearchHitThreadReplyInfo | null | undefined;
  deleted?: boolean | undefined;
  edited?: boolean | undefined;
  isFollowing?: boolean | undefined;
  /**
   * Message subtype (empty string for normal messages).
   */
  subtype?: string | undefined;
  localId?: string | undefined;
  meta?: { [k: string]: any } | null | undefined;
  savedTimestampMilli?: number | undefined;
  timestamp: Date;
  timestampMilli: number;
  /**
   * Same as `blocks`, with `highlight` annotations on matching text segments.
   */
  highlightedBlocks?: Array<MessageBlock> | undefined;
};

/** @internal */
export const SearchHitThreadRootInfo$inboundSchema: z.ZodType<
  SearchHitThreadRootInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  replyCount: types.optional(types.number()),
  lastReplyTimestampMilli: types.optional(types.number()),
});
/** @internal */
export type SearchHitThreadRootInfo$Outbound = {
  replyCount?: number | undefined;
  lastReplyTimestampMilli?: number | undefined;
};

/** @internal */
export const SearchHitThreadRootInfo$outboundSchema: z.ZodType<
  SearchHitThreadRootInfo$Outbound,
  z.ZodTypeDef,
  SearchHitThreadRootInfo
> = z.object({
  replyCount: z.number().int().optional(),
  lastReplyTimestampMilli: z.number().int().optional(),
});

export function searchHitThreadRootInfoToJSON(
  searchHitThreadRootInfo: SearchHitThreadRootInfo,
): string {
  return JSON.stringify(
    SearchHitThreadRootInfo$outboundSchema.parse(searchHitThreadRootInfo),
  );
}
export function searchHitThreadRootInfoFromJSON(
  jsonString: string,
): SafeParseResult<SearchHitThreadRootInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchHitThreadRootInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchHitThreadRootInfo' from JSON`,
  );
}

/** @internal */
export const SearchHitThreadReplyInfo$inboundSchema: z.ZodType<
  SearchHitThreadReplyInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  rootId: types.optional(types.string()),
  replySentToChannel: types.optional(types.boolean()),
  rootText: types.optional(types.string()),
});
/** @internal */
export type SearchHitThreadReplyInfo$Outbound = {
  rootId?: string | undefined;
  replySentToChannel?: boolean | undefined;
  rootText?: string | undefined;
};

/** @internal */
export const SearchHitThreadReplyInfo$outboundSchema: z.ZodType<
  SearchHitThreadReplyInfo$Outbound,
  z.ZodTypeDef,
  SearchHitThreadReplyInfo
> = z.object({
  rootId: z.string().optional(),
  replySentToChannel: z.boolean().optional(),
  rootText: z.string().optional(),
});

export function searchHitThreadReplyInfoToJSON(
  searchHitThreadReplyInfo: SearchHitThreadReplyInfo,
): string {
  return JSON.stringify(
    SearchHitThreadReplyInfo$outboundSchema.parse(searchHitThreadReplyInfo),
  );
}
export function searchHitThreadReplyInfoFromJSON(
  jsonString: string,
): SafeParseResult<SearchHitThreadReplyInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchHitThreadReplyInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchHitThreadReplyInfo' from JSON`,
  );
}

/** @internal */
export const SearchHit$inboundSchema: z.ZodType<
  SearchHit,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.string(),
  channelId: types.string(),
  workspaceId: types.string(),
  author: types.string(),
  authorAppId: z.nullable(types.string()).optional(),
  text: types.string(),
  blocks: z.nullable(z.array(MessageBlock$inboundSchema)).optional(),
  attachments: types.optional(z.array(z.record(z.any()))),
  files: types.optional(z.array(z.record(z.any()))),
  reactions: types.optional(z.array(Reaction$inboundSchema)),
  linkPreviews: types.optional(z.array(z.record(z.any()))),
  threadRootInfo: z.nullable(
    z.lazy(() => SearchHitThreadRootInfo$inboundSchema),
  ).optional(),
  threadReplyInfo: z.nullable(
    z.lazy(() => SearchHitThreadReplyInfo$inboundSchema),
  ).optional(),
  deleted: types.optional(types.boolean()),
  edited: types.optional(types.boolean()),
  isFollowing: types.optional(types.boolean()),
  subtype: types.optional(types.string()),
  localId: types.optional(types.string()),
  meta: z.nullable(z.record(z.any())).optional(),
  savedTimestampMilli: types.optional(types.number()),
  timestamp: types.date(),
  timestampMilli: types.number(),
  highlightedBlocks: types.optional(z.array(MessageBlock$inboundSchema)),
});
/** @internal */
export type SearchHit$Outbound = {
  id: string;
  channelId: string;
  workspaceId: string;
  author: string;
  authorAppId?: string | null | undefined;
  text: string;
  blocks?: Array<MessageBlock$Outbound> | null | undefined;
  attachments?: Array<{ [k: string]: any }> | undefined;
  files?: Array<{ [k: string]: any }> | undefined;
  reactions?: Array<Reaction$Outbound> | undefined;
  linkPreviews?: Array<{ [k: string]: any }> | undefined;
  threadRootInfo?: SearchHitThreadRootInfo$Outbound | null | undefined;
  threadReplyInfo?: SearchHitThreadReplyInfo$Outbound | null | undefined;
  deleted?: boolean | undefined;
  edited?: boolean | undefined;
  isFollowing?: boolean | undefined;
  subtype?: string | undefined;
  localId?: string | undefined;
  meta?: { [k: string]: any } | null | undefined;
  savedTimestampMilli?: number | undefined;
  timestamp: string;
  timestampMilli: number;
  highlightedBlocks?: Array<MessageBlock$Outbound> | undefined;
};

/** @internal */
export const SearchHit$outboundSchema: z.ZodType<
  SearchHit$Outbound,
  z.ZodTypeDef,
  SearchHit
> = z.object({
  id: z.string(),
  channelId: z.string(),
  workspaceId: z.string(),
  author: z.string(),
  authorAppId: z.nullable(z.string()).optional(),
  text: z.string(),
  blocks: z.nullable(z.array(MessageBlock$outboundSchema)).optional(),
  attachments: z.array(z.record(z.any())).optional(),
  files: z.array(z.record(z.any())).optional(),
  reactions: z.array(Reaction$outboundSchema).optional(),
  linkPreviews: z.array(z.record(z.any())).optional(),
  threadRootInfo: z.nullable(
    z.lazy(() => SearchHitThreadRootInfo$outboundSchema),
  ).optional(),
  threadReplyInfo: z.nullable(
    z.lazy(() => SearchHitThreadReplyInfo$outboundSchema),
  ).optional(),
  deleted: z.boolean().optional(),
  edited: z.boolean().optional(),
  isFollowing: z.boolean().optional(),
  subtype: z.string().optional(),
  localId: z.string().optional(),
  meta: z.nullable(z.record(z.any())).optional(),
  savedTimestampMilli: z.number().int().optional(),
  timestamp: z.date().transform(v => v.toISOString()),
  timestampMilli: z.number().int(),
  highlightedBlocks: z.array(MessageBlock$outboundSchema).optional(),
});

export function searchHitToJSON(searchHit: SearchHit): string {
  return JSON.stringify(SearchHit$outboundSchema.parse(searchHit));
}
export function searchHitFromJSON(
  jsonString: string,
): SafeParseResult<SearchHit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchHit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchHit' from JSON`,
  );
}
