/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b1f5e5846e95
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type UserGroup = {
  id: string;
  name: string;
  handle: string;
  description?: string | null | undefined;
  disabled?: boolean | undefined;
  createdBy?: string | undefined;
  workspaceId: string;
  workspaceUserIds?: Array<string> | undefined;
};

/** @internal */
export const UserGroup$inboundSchema: z.ZodType<
  UserGroup,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  handle: types.string(),
  description: z.nullable(types.string()).optional(),
  disabled: types.optional(types.boolean()),
  createdBy: types.optional(types.string()),
  workspaceId: types.string(),
  workspaceUserIds: types.optional(z.array(types.string())),
});
/** @internal */
export type UserGroup$Outbound = {
  id: string;
  name: string;
  handle: string;
  description?: string | null | undefined;
  disabled?: boolean | undefined;
  createdBy?: string | undefined;
  workspaceId: string;
  workspaceUserIds?: Array<string> | undefined;
};

/** @internal */
export const UserGroup$outboundSchema: z.ZodType<
  UserGroup$Outbound,
  z.ZodTypeDef,
  UserGroup
> = z.object({
  id: z.string(),
  name: z.string(),
  handle: z.string(),
  description: z.nullable(z.string()).optional(),
  disabled: z.boolean().optional(),
  createdBy: z.string().optional(),
  workspaceId: z.string(),
  workspaceUserIds: z.array(z.string()).optional(),
});

export function userGroupToJSON(userGroup: UserGroup): string {
  return JSON.stringify(UserGroup$outboundSchema.parse(userGroup));
}
export function userGroupFromJSON(
  jsonString: string,
): SafeParseResult<UserGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGroup' from JSON`,
  );
}
