/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aa17bd9a89ba
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Lifecycle state of a workspace user.
 */
export const UserStatus = {
  Activated: "ACTIVATED",
  Deactivated: "DEACTIVATED",
  Invited: "INVITED",
} as const;
/**
 * Lifecycle state of a workspace user.
 */
export type UserStatus = OpenEnum<typeof UserStatus>;

/** @internal */
export const UserStatus$inboundSchema: z.ZodType<
  UserStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(UserStatus);
/** @internal */
export const UserStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  UserStatus
> = openEnums.outboundSchema(UserStatus);
