/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6ac81a7b49b9
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  Avatar,
  Avatar$inboundSchema,
  Avatar$Outbound,
  Avatar$outboundSchema,
} from "./avatar.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  UserRole,
  UserRole$inboundSchema,
  UserRole$outboundSchema,
} from "./user-role.js";
import {
  UserStatus,
  UserStatus$inboundSchema,
  UserStatus$outboundSchema,
} from "./user-status.js";

/**
 * A user's custom status (the value, not the update payload).
 */
export type CustomStatus = {
  /**
   * Emoji code in `:emoji_name:` form.
   */
  code?: string | undefined;
  /**
   * Free-form status text.
   */
  status?: string | undefined;
  /**
   * Expiration mode (e.g. `custom`, `dont_clear`).
   */
  expiration?: string | undefined;
  /**
   * Epoch-ms moment the status auto-clears (0 if never).
   */
  expiresAt?: number | undefined;
  showUntil?: boolean | undefined;
};

export type User = {
  id: string;
  email: string;
  name: string;
  phone?: string | undefined;
  /**
   * User's job title (empty string if unset).
   */
  title?: string | undefined;
  /**
   * Workspace role.
   */
  role: UserRole;
  /**
   * Lifecycle state of a workspace user.
   */
  status: UserStatus;
  workspaceId: string;
  avatar?: Avatar | undefined;
  customStatus?: CustomStatus | null | undefined;
  timeZoneId?: string | undefined;
  automaticallyTimeZone?: boolean | undefined;
  activeUntil?: number | undefined;
  isAddonBot?: boolean | undefined;
  isPumbleBot?: boolean | undefined;
  invitedBy?: string | null | undefined;
  broadcastWarningShownTs?: number | null | undefined;
};

/** @internal */
export const CustomStatus$inboundSchema: z.ZodType<
  CustomStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: types.optional(types.string()),
  status: types.optional(types.string()),
  expiration: types.optional(types.string()),
  expiresAt: types.optional(types.number()),
  showUntil: types.optional(types.boolean()),
});
/** @internal */
export type CustomStatus$Outbound = {
  code?: string | undefined;
  status?: string | undefined;
  expiration?: string | undefined;
  expiresAt?: number | undefined;
  showUntil?: boolean | undefined;
};

/** @internal */
export const CustomStatus$outboundSchema: z.ZodType<
  CustomStatus$Outbound,
  z.ZodTypeDef,
  CustomStatus
> = z.object({
  code: z.string().optional(),
  status: z.string().optional(),
  expiration: z.string().optional(),
  expiresAt: z.number().int().optional(),
  showUntil: z.boolean().optional(),
});

export function customStatusToJSON(customStatus: CustomStatus): string {
  return JSON.stringify(CustomStatus$outboundSchema.parse(customStatus));
}
export function customStatusFromJSON(
  jsonString: string,
): SafeParseResult<CustomStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomStatus' from JSON`,
  );
}

/** @internal */
export const User$inboundSchema: z.ZodType<User, z.ZodTypeDef, unknown> = z
  .object({
    id: types.string(),
    email: types.string(),
    name: types.string(),
    phone: types.optional(types.string()),
    title: types.optional(types.string()),
    role: UserRole$inboundSchema,
    status: UserStatus$inboundSchema,
    workspaceId: types.string(),
    avatar: types.optional(Avatar$inboundSchema),
    customStatus: z.nullable(z.lazy(() => CustomStatus$inboundSchema))
      .optional(),
    timeZoneId: types.optional(types.string()),
    automaticallyTimeZone: types.optional(types.boolean()),
    activeUntil: types.optional(types.number()),
    isAddonBot: types.optional(types.boolean()),
    isPumbleBot: types.optional(types.boolean()),
    invitedBy: z.nullable(types.string()).optional(),
    broadcastWarningShownTs: z.nullable(types.number()).optional(),
  });
/** @internal */
export type User$Outbound = {
  id: string;
  email: string;
  name: string;
  phone?: string | undefined;
  title?: string | undefined;
  role: string;
  status: string;
  workspaceId: string;
  avatar?: Avatar$Outbound | undefined;
  customStatus?: CustomStatus$Outbound | null | undefined;
  timeZoneId?: string | undefined;
  automaticallyTimeZone?: boolean | undefined;
  activeUntil?: number | undefined;
  isAddonBot?: boolean | undefined;
  isPumbleBot?: boolean | undefined;
  invitedBy?: string | null | undefined;
  broadcastWarningShownTs?: number | null | undefined;
};

/** @internal */
export const User$outboundSchema: z.ZodType<User$Outbound, z.ZodTypeDef, User> =
  z.object({
    id: z.string(),
    email: z.string(),
    name: z.string(),
    phone: z.string().optional(),
    title: z.string().optional(),
    role: UserRole$outboundSchema,
    status: UserStatus$outboundSchema,
    workspaceId: z.string(),
    avatar: Avatar$outboundSchema.optional(),
    customStatus: z.nullable(z.lazy(() => CustomStatus$outboundSchema))
      .optional(),
    timeZoneId: z.string().optional(),
    automaticallyTimeZone: z.boolean().optional(),
    activeUntil: z.number().int().optional(),
    isAddonBot: z.boolean().optional(),
    isPumbleBot: z.boolean().optional(),
    invitedBy: z.nullable(z.string()).optional(),
    broadcastWarningShownTs: z.nullable(z.number().int()).optional(),
  });

export function userToJSON(user: User): string {
  return JSON.stringify(User$outboundSchema.parse(user));
}
export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
