/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Avatar = {
  fullPath?: string | undefined;
  scaledPath?: string | undefined;
};

/** @internal */
export const Avatar$inboundSchema: z.ZodType<Avatar, z.ZodTypeDef, unknown> = z
  .object({
    fullPath: types.optional(types.string()),
    scaledPath: types.optional(types.string()),
  });
/** @internal */
export type Avatar$Outbound = {
  fullPath?: string | undefined;
  scaledPath?: string | undefined;
};

/** @internal */
export const Avatar$outboundSchema: z.ZodType<
  Avatar$Outbound,
  z.ZodTypeDef,
  Avatar
> = z.object({
  fullPath: z.string().optional(),
  scaledPath: z.string().optional(),
});

export function avatarToJSON(avatar: Avatar): string {
  return JSON.stringify(Avatar$outboundSchema.parse(avatar));
}
export function avatarFromJSON(
  jsonString: string,
): SafeParseResult<Avatar, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Avatar$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Avatar' from JSON`,
  );
}
