/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Lightweight reference returned by `createChannel`.
 */
export type ChannelRef = {
  id: string;
  name: string;
};

/** @internal */
export const ChannelRef$inboundSchema: z.ZodType<
  ChannelRef,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});
/** @internal */
export type ChannelRef$Outbound = {
  id: string;
  name: string;
};

/** @internal */
export const ChannelRef$outboundSchema: z.ZodType<
  ChannelRef$Outbound,
  z.ZodTypeDef,
  ChannelRef
> = z.object({
  id: z.string(),
  name: z.string(),
});

export function channelRefToJSON(channelRef: ChannelRef): string {
  return JSON.stringify(ChannelRef$outboundSchema.parse(channelRef));
}
export function channelRefFromJSON(
  jsonString: string,
): SafeParseResult<ChannelRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChannelRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChannelRef' from JSON`,
  );
}
