/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const PostingPermissionsGroup = {
  Everyone: "EVERYONE",
  WorkspaceAdmins: "WORKSPACE_ADMINS",
  SpecificUsers: "SPECIFIC_USERS",
} as const;
export type PostingPermissionsGroup = OpenEnum<typeof PostingPermissionsGroup>;

/** @internal */
export const PostingPermissionsGroup$inboundSchema: z.ZodType<
  PostingPermissionsGroup,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PostingPermissionsGroup);
/** @internal */
export const PostingPermissionsGroup$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  PostingPermissionsGroup
> = openEnums.outboundSchema(PostingPermissionsGroup);
