/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const RecurrenceType = {
  Daily: "DAILY",
  Businessdays: "BUSINESSDAYS",
  Weekly: "WEEKLY",
  Biweekly: "BIWEEKLY",
  MonthlyNthWeekday: "MONTHLY_NTH_WEEKDAY",
  MonthlyLastWeekday: "MONTHLY_LAST_WEEKDAY",
  QuarterlyNthWeekday: "QUARTERLY_NTH_WEEKDAY",
  QuarterlyLastWeekday: "QUARTERLY_LAST_WEEKDAY",
  Annually: "ANNUALLY",
} as const;
export type RecurrenceType = OpenEnum<typeof RecurrenceType>;

/** @internal */
export const RecurrenceType$inboundSchema: z.ZodType<
  RecurrenceType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(RecurrenceType);
/** @internal */
export const RecurrenceType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  RecurrenceType
> = openEnums.outboundSchema(RecurrenceType);
