/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const SearchStrategy = {
  MostRelevant: "MOST_RELEVANT",
  MostRecent: "MOST_RECENT",
  Newest: "NEWEST",
  Oldest: "OLDEST",
} as const;
export type SearchStrategy = ClosedEnum<typeof SearchStrategy>;

/** @internal */
export const SearchStrategy$inboundSchema: z.ZodNativeEnum<
  typeof SearchStrategy
> = z.nativeEnum(SearchStrategy);
/** @internal */
export const SearchStrategy$outboundSchema: z.ZodNativeEnum<
  typeof SearchStrategy
> = SearchStrategy$inboundSchema;
