/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Workspace role.
 */
export const UserRole = {
  Owner: "OWNER",
  Admin: "ADMIN",
  Member: "MEMBER",
  Guest: "GUEST",
} as const;
/**
 * Workspace role.
 */
export type UserRole = OpenEnum<typeof UserRole>;

/** @internal */
export const UserRole$inboundSchema: z.ZodType<
  UserRole,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(UserRole);
/** @internal */
export const UserRole$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  UserRole
> = openEnums.outboundSchema(UserRole);
